<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_profile</name>
   <tag></tag>
   <elementGuidId>eac81229-b4e2-4c8b-9a61-90449c9d5d51</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='dropdownBasic2']/div[2]/i</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>i.ft-chevron-down</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@class = 'ft-chevron-down']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>ec7f3774-3960-4f20-8d26-9c70c1d38326</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ft-chevron-down</value>
      <webElementGuid>a84f3b66-b754-456a-ae4e-546b32c804ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dropdownBasic2&quot;)/div[2]/i[@class=&quot;ft-chevron-down&quot;]</value>
      <webElementGuid>3584a387-9871-4e50-a12a-f46e28df37f6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='dropdownBasic2']/div[2]/i</value>
      <webElementGuid>fa844623-08c4-46ee-84da-a677710394f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/i</value>
      <webElementGuid>d7079626-63ac-44c5-8563-ea25a98b3f29</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
