<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>buttonNextPage</name>
   <tag></tag>
   <elementGuidId>8bb2d489-bb64-457a-857f-e4ebcdc7e4e0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value></value>
      <webElementGuid>093540ad-323b-43b0-8291-d6e999415b4b</webElementGuid>
   </webElementProperties>
</WebElementEntity>
