<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Hit OCR</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>677da6b2-1b5d-4fab-9607-e74e249c2946</testSuiteGuid>
   <testCaseLink>
      <guid>b4782e55-d747-437f-82ea-3cc15820dac3</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/OCR Testing/API Only/MAIN_BPKB Only</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5a45758c-96a9-49a2-8d9a-1aaddf4627e5</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6f6f6151-e84b-4a62-88e4-b99e811b43d9</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>98df8210-7880-499c-b9aa-cbcf11396947</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/OCR Testing/API Only/MAIN_KK Only</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6d895cc1-d59c-4a83-a8d6-03e07a06cc86</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>60a228e7-4d74-4303-b499-b7d0a9169267</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>6756f38d-6b92-4e77-9284-cc57671e386c</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/OCR Testing/API Only/MAIN_KTP Only</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d66057d3-a928-470a-9612-77031ed6f443</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0c31d039-f48c-4008-a68a-c806d37a4d67</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>843fea19-5ac9-4796-abc4-7e46b3e8820d</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/OCR Testing/API Only/MAIN_NPWP Only</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f2b79dec-d92c-4994-a814-0a28d8bce816</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>caf101da-0928-460e-8c72-25056a33450c</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>9d25b4aa-9dc1-42b1-9581-c2eb56f4dd2b</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/OCR Testing/API Only/MAIN_Passport Only</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>96601b94-4eac-4e58-9ec6-bc612dec9325</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>90132161-6d55-4a0b-8ccb-1f989ed72db2</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>bb9faaea-08a8-4391-b3c7-0fa9754bfcb0</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/OCR Testing/API Only/MAIN_RK BCA Only</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4f7003cd-d0f4-4b02-956c-0cef086cfe4e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3cd6741e-0553-460c-a904-ff6630da395b</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>7684e36f-d033-426e-b44b-a66fb1384745</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/OCR Testing/API Only/MAIN_RK Mandiri Only</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f3e5db2d-7158-4668-b705-148232297158</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>afe28376-d57c-42e3-9a7e-adf52b767dd5</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>cfae21cd-8482-4cc9-bffd-14011e4a0622</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/OCR Testing/API Only/MAIN_STNK Only</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7c02a436-222f-4bca-abe0-8a233f73b753</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7d4c8a67-9ab8-4082-acfd-62e4569b75d1</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>7d8cc142-70ca-4015-be41-e308156c8d88</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/OCR Testing/API Only/MAIN_RK BRI Only</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e1992526-011e-4d31-aea9-503784efd183</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a40dee0a-e38a-436d-b993-61f5502ec410</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
