<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__confirmnewPass</name>
   <tag></tag>
   <elementGuidId>d97303be-5ea7-44bc-ae6c-b3f7a5c97a04</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#confirmNewPassword</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='confirmNewPassword']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f0cfc960-0982-4152-9dd2-39e0cb17d7a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ng-untouched ng-pristine ng-invalid</value>
      <webElementGuid>e672b637-de0e-475c-a2e2-8226a654047f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-name</name>
      <type>Main</type>
      <value>confirmNewPassword</value>
      <webElementGuid>13c31895-21e9-4586-a02c-4629c5e2582b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>confirmNewPassword</value>
      <webElementGuid>4f137a86-948e-4531-9eda-b00ee923c332</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>868b9462-0ce4-46c7-be83-4b77838621a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Confirm new password</value>
      <webElementGuid>9d224e2b-ca98-4b60-93c9-91c3c33da02c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>01b5685a-b7ee-4923-82ef-e4fae9eb456c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;confirmNewPassword&quot;)</value>
      <webElementGuid>a94ec655-58bb-4d66-ae40-992dbab5ef71</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='confirmNewPassword']</value>
      <webElementGuid>91fae303-97a1-44e8-9d5c-8b7ad7ba8119</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='msxForm']/div/div[3]/app-question/app-password/fieldset/div/input</value>
      <webElementGuid>476bc922-644d-4edc-bcb0-5f635f00c9cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/app-question/app-password/fieldset/div/input</value>
      <webElementGuid>1d17fd47-6ef9-421a-99e9-b9f096f5088c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'confirmNewPassword' and @type = 'password' and @placeholder = 'Confirm new password']</value>
      <webElementGuid>7eb90b62-b986-456e-b2ca-031c0104bbe7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
