<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_TipeIsiUlang</name>
   <tag></tag>
   <elementGuidId>c22ffc32-7faa-4d44-89a0-2baa31da35ce</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;topupTypeCode&quot;]/div/span[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;topupTypeCode&quot;]/div/span[2]</value>
      <webElementGuid>43117eb5-88af-4792-83b8-aeb3839aecc2</webElementGuid>
   </webElementProperties>
</WebElementEntity>
