<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Tenant</name>
   <tag></tag>
   <elementGuidId>91ef2112-2fc2-43ef-b900-cde3b3863c92</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;tenantCode&quot;]/div/span[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;tenantCode&quot;]/div/span[2]</value>
      <webElementGuid>c5a1593e-d0ad-41ec-ae81-803e1ff4cf52</webElementGuid>
   </webElementProperties>
</WebElementEntity>
