<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>catatan</name>
   <tag></tag>
   <elementGuidId>4b466a32-88d7-4fdf-98d4-ca8b5c5744b4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value></value>
      <webElementGuid>c8d11b97-0047-4c9d-a1ca-153e6907e727</webElementGuid>
   </webElementProperties>
</WebElementEntity>
