<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>KantorLocation</name>
   <tag></tag>
   <elementGuidId>06bdff53-2e6a-4284-8c3f-a457fa1381bc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value></value>
      <webElementGuid>9cebb3e3-c03e-431b-8562-b79094a145c6</webElementGuid>
   </webElementProperties>
</WebElementEntity>
