<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>modifyobject</name>
   <tag></tag>
   <elementGuidId>f6a2ff12-6dc9-4a7b-ba5d-4df6a76caed9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value></value>
      <webElementGuid>fbd48cbd-950d-48e2-8a72-20ccc9ab2d02</webElementGuid>
   </webElementProperties>
</WebElementEntity>
