<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>NamaSaldo</name>
   <tag></tag>
   <elementGuidId>a5ef71fb-f3f0-4298-bff8-22badce878c9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value></value>
      <webElementGuid>6ffcf8c6-cf9a-4160-af4d-199abb81e8a7</webElementGuid>
   </webElementProperties>
</WebElementEntity>
