<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>procTrx</name>
   <tag></tag>
   <elementGuidId>9c8ee179-48ba-457f-8c56-100d46208f96</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value></value>
      <webElementGuid>9f27ef6b-e7b0-4820-b8dd-de6b1d8d639b</webElementGuid>
   </webElementProperties>
</WebElementEntity>
