<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>refTrx</name>
   <tag></tag>
   <elementGuidId>93c4cfe0-68c5-403d-8f76-891c89029543</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value></value>
      <webElementGuid>2fd2129e-2e16-48de-8ea9-eba6acffd538</webElementGuid>
   </webElementProperties>
</WebElementEntity>
