<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Saldo</name>
   <tag></tag>
   <elementGuidId>3903bcf2-fa36-4a3a-b632-bf6a278530da</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value></value>
      <webElementGuid>b98401f6-39b6-4f86-9bb9-262096268787</webElementGuid>
   </webElementProperties>
</WebElementEntity>
