<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>TenantTrx</name>
   <tag></tag>
   <elementGuidId>20084d2b-3ecb-4d91-b4bb-ecac64335c2a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value></value>
      <webElementGuid>84a25bd7-28a5-4d98-82a4-4991920cb836</webElementGuid>
   </webElementProperties>
</WebElementEntity>
