<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>TglTrx</name>
   <tag></tag>
   <elementGuidId>ff574120-c1eb-4c4b-8cd6-928881f3caaf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value></value>
      <webElementGuid>43f80946-fe7b-463c-b4c2-a232817465a4</webElementGuid>
   </webElementProperties>
</WebElementEntity>
