<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>gotoLast_page</name>
   <tag></tag>
   <elementGuidId>f2150cbd-d1ac-449f-9745-cb225d0d3276</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>i.datatable-icon-skip</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//datatable-pager/ul/li[6]/a/i</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@class = 'datatable-icon-skip']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>fbeeee5a-6451-4c26-9ebc-5985d3059b12</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>datatable-icon-skip</value>
      <webElementGuid>8845c0d3-af0b-4b59-ba06-89139069b5cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;vertical-layout navbar-static menu-hide page-scrolled navbar-scrolled pace-done&quot;]/app-root[1]/app-full-layout[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;wrapper&quot;]/div[@class=&quot;main-panel&quot;]/div[@class=&quot;main-content&quot;]/div[@class=&quot;content-wrapper&quot;]/app-list-roles[@class=&quot;ng-star-inserted&quot;]/app-msx-paging[1]/app-msx-datatable[@class=&quot;ng-star-inserted&quot;]/section[@class=&quot;msx-datatable&quot;]/ngx-datatable[@class=&quot;ngx-datatable material bootstrap fixed-header virtualized selectable checkbox-selection&quot;]/div[@class=&quot;visible&quot;]/datatable-footer[@class=&quot;datatable-footer ng-star-inserted&quot;]/div[@class=&quot;datatable-footer-inner&quot;]/datatable-pager[@class=&quot;datatable-pager ng-star-inserted&quot;]/ul[@class=&quot;pager&quot;]/li[6]/a[1]/i[@class=&quot;datatable-icon-skip&quot;]</value>
      <webElementGuid>0b0ae551-022c-4c81-a017-0091b1e6c193</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//datatable-pager/ul/li[6]/a/i</value>
      <webElementGuid>f29dd70e-8eab-4818-8cfb-4716acf57fa0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
