<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_Catatan_datatable-icon-right</name>
   <tag></tag>
   <elementGuidId>47fe5917-44f7-4033-97e3-2a24c28275dc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>i.datatable-icon-right</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@class=&quot;datatable-icon-right&quot;]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@class=&quot;datatable-icon-right&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>273557d2-494a-4fcc-917d-3ca4a4060cb4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>datatable-icon-right</value>
      <webElementGuid>ca6e2c2b-c731-4ac5-af59-12c405de83f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@class=&quot;datatable-icon-right&quot;]</value>
      <webElementGuid>70888aa8-020f-4d5c-bb82-79e280daa756</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[6]/a/i</value>
      <webElementGuid>c6c58f38-9480-4530-b4dd-eabd3b4878b3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
