<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>skiptoLast_page</name>
   <tag></tag>
   <elementGuidId>87cf8668-3896-46bc-b74b-bd1866a12bb5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>i.datatable-icon-skip</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//datatable-pager/ul/li[6]/a/i</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@class = 'datatable-icon-skip']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>50efe011-b84f-4f94-b32b-ee0ecc92a3b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>datatable-icon-skip</value>
      <webElementGuid>55b94023-3b33-40aa-a51f-f36b91fed074</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;vertical-layout navbar-static menu-hide page-scrolled navbar-scrolled pace-done&quot;]/app-root[1]/app-full-layout[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;wrapper&quot;]/div[@class=&quot;main-panel&quot;]/div[@class=&quot;main-content&quot;]/div[@class=&quot;content-wrapper&quot;]/app-list-roles[@class=&quot;ng-star-inserted&quot;]/app-msx-paging[1]/app-msx-datatable[@class=&quot;ng-star-inserted&quot;]/section[@class=&quot;msx-datatable&quot;]/ngx-datatable[@class=&quot;ngx-datatable material bootstrap fixed-header virtualized selectable checkbox-selection&quot;]/div[@class=&quot;visible&quot;]/datatable-footer[@class=&quot;datatable-footer ng-star-inserted&quot;]/div[@class=&quot;datatable-footer-inner&quot;]/datatable-pager[@class=&quot;datatable-pager ng-star-inserted&quot;]/ul[@class=&quot;pager&quot;]/li[6]/a[1]/i[@class=&quot;datatable-icon-skip&quot;]</value>
      <webElementGuid>12c2e32d-b1e8-424a-8481-696ae1213366</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//datatable-pager/ul/li[6]/a/i</value>
      <webElementGuid>f8941ad3-f2ad-47e0-9aca-de986ced90a4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
