<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>trxNumViewBukti</name>
   <tag></tag>
   <elementGuidId>4a1811a2-103a-4aad-8c71-0f2ed34a3a68</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>/html/body/ngb-modal-window/div/div/app-view-payment-proof/div/div[2]/div[1]/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/ngb-modal-window/div/div/app-view-payment-proof/div/div[2]/div[1]/input</value>
      <webElementGuid>7f2ca206-5c1f-4e5d-854b-0cfcb7704098</webElementGuid>
   </webElementProperties>
</WebElementEntity>
