<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_ListCustomer</name>
   <tag></tag>
   <elementGuidId>7ce6f056-4cc2-4764-b8d6-047ab4d48523</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;_0rif_mat-tab-content-0-0&quot;]/div/storage-bucket-details-objects/storage-objects-table/storage-drop-target/div[2]/storage-objects-breadcrumb/div/cfc-breadcrumbs/div/div/ol/li[6]/cfc-breadcrumb-link-item/div/a/span[2]/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
