<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>inputSearchFilter</name>
   <tag></tag>
   <elementGuidId>5290d063-eefd-42cd-ad5c-a6b6c7332e55</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//mat-tab-body[@id='_0rif_mat-tab-content-0-0']/div/storage-bucket-details-objects/storage-objects-table/storage-drop-target/div[2]/cfc-table/div[2]/div/div/cfc-filter-basic/div[2]/cfc-filter-basic-input/div/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.cfctest-filter-basic-input.cfc-filter-input.cfc-outline-focus-indicator</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>f2e65561-d734-4dae-ae0d-af20784672f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>3b560864-82f9-4e7d-b516-2576c783fdc9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>textbox</value>
      <webElementGuid>e93a636b-d6d6-456d-8b14-23d61a69b8e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>0396b41e-2d7d-4fbf-a63d-9f2d9cddc90b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocapitalize</name>
      <type>Main</type>
      <value>none</value>
      <webElementGuid>c85ca96f-e459-4bc5-91f6-21bb59710ad4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>spellcheck</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>d34305ee-ba4e-471f-8d02-491deda561cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>cfctest-filter-basic-input cfc-filter-input cfc-outline-focus-indicator</value>
      <webElementGuid>d634882a-08a2-4f37-9154-19a8f9f87439</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Filter objects and folders</value>
      <webElementGuid>a2d98ed1-28ca-43fc-a835-594375ece5c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>_0rif_filter-label-goog_1566579324</value>
      <webElementGuid>f171a179-2836-4ce5-a448-5ea0dcbbb8cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>contenteditable</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>95a2361f-e9d8-4e0a-b767-df3c5c871de2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>sandboxuid</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>b1fb9c6f-db55-4d3f-aeba-d1d20bcdbc5e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;_0rif_mat-tab-content-0-0&quot;)/div[@class=&quot;mat-mdc-tab-body-content ng-tns-c2396234108-0 ng-trigger ng-trigger-translateTab&quot;]/storage-bucket-details-objects[@class=&quot;cfc-gutter-base ng-star-inserted&quot;]/storage-objects-table[@class=&quot;cfc-height-full&quot;]/storage-drop-target[1]/div[@class=&quot;storage-drop-target-content&quot;]/cfc-table[@class=&quot;cfc-full-bleed cfc-full-bleed-keep-top-padding&quot;]/div[2]/div[1]/div[@class=&quot;cfc-table-filter-container cfc-table-top-border ng-star-inserted&quot;]/cfc-filter-basic[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;cfc-filter-edit-area&quot;]/cfc-filter-basic-input[1]/div[@class=&quot;cfc-filter-input-container&quot;]/div[@class=&quot;cfctest-filter-basic-input cfc-filter-input cfc-outline-focus-indicator&quot;]</value>
      <webElementGuid>e82c2c49-3357-453c-938a-54366ca4449d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//mat-tab-body[@id='_0rif_mat-tab-content-0-0']/div/storage-bucket-details-objects/storage-objects-table/storage-drop-target/div[2]/cfc-table/div[2]/div/div/cfc-filter-basic/div[2]/cfc-filter-basic-input/div/div</value>
      <webElementGuid>4a125933-b294-48c1-a16e-ebf675993034</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//cfc-filter-basic-input/div/div</value>
      <webElementGuid>79dec375-0a2c-4b82-8694-f30eb18ea38e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@placeholder = 'Filter objects and folders']</value>
      <webElementGuid>53432b97-8374-4456-b072-6b7e4c9bca17</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
