<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>SaldoMenu</name>
   <tag></tag>
   <elementGuidId>97d29087-41ca-4b78-bcc5-b234330b3607</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@href = '/balance']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-parent</name>
      <type>Main</type>
      <value>Balance</value>
      <webElementGuid>622c8589-81a6-480a-a60b-d0a9bfab0571</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/balance</value>
      <webElementGuid>f34feb5e-fdf6-4d90-84af-a89fc8f0a08a</webElementGuid>
   </webElementProperties>
</WebElementEntity>
