<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_New</name>
   <tag></tag>
   <elementGuidId>e788b7cb-cdd2-49e7-a491-ef7e8ff128f9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.msx-action.btn.btn-primary.ng-star-inserted</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[contains(text(),'New')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>3ad4aafd-8e64-4f2b-8d29-e73bfe8a7991</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>msx-action btn btn-primary ng-star-inserted</value>
      <webElementGuid>2c81548e-4616-4847-aeb4-8313da85f895</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-ng-class</name>
      <type>Main</type>
      <value>btn btn-primary</value>
      <webElementGuid>59b9f200-edb2-4117-a168-09aaced4f48e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> New</value>
      <webElementGuid>32f0368d-0fbc-47d8-95fb-14331a49683b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;vertical-layout navbar-static menu-hide pace-done menu-expanded&quot;]/app-root[1]/app-full-layout[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;wrapper&quot;]/div[@class=&quot;main-panel&quot;]/div[@class=&quot;main-content&quot;]/div[@class=&quot;content-wrapper&quot;]/app-list-roles[@class=&quot;ng-star-inserted&quot;]/app-msx-paging[1]/div[@class=&quot;row&quot;]/div[@class=&quot;col-6 text-right&quot;]/a[@class=&quot;msx-action btn btn-primary ng-star-inserted&quot;]</value>
      <webElementGuid>12a606fa-fdd1-48ad-9ca1-b350b994cb0a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'New')]</value>
      <webElementGuid>787a8187-c66b-4784-9dd7-98d4ac9115e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='List Roles'])[2]/following::a[1]</value>
      <webElementGuid>1e929555-11d2-4017-8bb8-bb25969df7e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Coupon'])[1]/following::a[1]</value>
      <webElementGuid>8e241b1c-1d5c-45ac-95f7-25f6cd07d7f1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Filter'])[1]/preceding::a[1]</value>
      <webElementGuid>fa72794f-50cc-4a26-ad82-4392bd33a424</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Role Name'])[1]/preceding::a[1]</value>
      <webElementGuid>149a9c01-01cd-4264-b861-130d27fa0ee9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='New']/parent::*</value>
      <webElementGuid>9639aad0-788a-441d-bf56-60a790cf0d26</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/a</value>
      <webElementGuid>7a1c5759-da6d-45af-8368-84836cf7ca2a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[(text() = ' New' or . = ' New')]</value>
      <webElementGuid>e3349ab8-c860-4402-85ce-c8686bee64ba</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
