<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>MaxPage</name>
   <tag></tag>
   <elementGuidId>b0cb0e5c-5a4b-426c-a916-0d5a3a840a63</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value></value>
      <webElementGuid>0922639f-d3c4-41f3-9a02-b5acb00a8824</webElementGuid>
   </webElementProperties>
</WebElementEntity>
