<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>next_page</name>
   <tag></tag>
   <elementGuidId>7fca4252-0bdc-4c23-a0b8-617ec27011ff</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//datatable-pager/ul/li[5]/a/i</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>i.datatable-icon-right</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@class = 'datatable-icon-right']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>19292842-2202-4f0b-bf00-d67adbbb748b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>datatable-icon-right</value>
      <webElementGuid>1809a5b3-8b7e-48c4-806d-0e2a602a9a23</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;vertical-layout navbar-static menu-hide page-scrolled navbar-scrolled pace-done&quot;]/app-root[1]/app-full-layout[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;wrapper&quot;]/div[@class=&quot;main-panel&quot;]/div[@class=&quot;main-content&quot;]/div[@class=&quot;content-wrapper&quot;]/app-list-roles[@class=&quot;ng-star-inserted&quot;]/app-msx-paging[1]/app-msx-datatable[@class=&quot;ng-star-inserted&quot;]/section[@class=&quot;msx-datatable&quot;]/ngx-datatable[@class=&quot;ngx-datatable material bootstrap fixed-header virtualized selectable checkbox-selection&quot;]/div[@class=&quot;visible&quot;]/datatable-footer[@class=&quot;datatable-footer ng-star-inserted&quot;]/div[@class=&quot;datatable-footer-inner&quot;]/datatable-pager[@class=&quot;datatable-pager ng-star-inserted&quot;]/ul[@class=&quot;pager&quot;]/li[5]/a[1]/i[@class=&quot;datatable-icon-right&quot;]</value>
      <webElementGuid>2f8fe9a1-b098-4478-bf87-c3aa56b8346b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//datatable-pager/ul/li[5]/a/i</value>
      <webElementGuid>4dcff16a-3c9f-43af-89a3-55dffb811eb9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
