<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>tombolX_menu</name>
   <tag></tag>
   <elementGuidId>00feb0da-6313-47e0-93c7-b4ef4e850dfa</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='sidebarClose']/i</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>i.ft-x.ng-tns-c133-2</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = 'sidebarClose']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>73f241f6-e4d7-47be-a347-5a0be9a51684</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>nav-close d-block d-lg-block d-xl-none ng-tns-c133-4</value>
      <webElementGuid>90117900-48e3-403d-b146-a48838b25383</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;sidebarClose&quot;)/i[@class=&quot;ft-x ng-tns-c133-2&quot;]</value>
      <webElementGuid>f19c05f0-ccf1-471e-9d35-c486e4962231</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>sidebarClose</value>
      <webElementGuid>681e5e8a-f6f9-4cc7-9d6f-88778dd4e5bf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='sidebarClose']/i</value>
      <webElementGuid>dee706dd-8b00-4840-8be1-d23649849a0d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[3]/i</value>
      <webElementGuid>4ffc0433-f92a-4b8d-bb69-fa84f6182e5b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
