<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>tombolX_menu</name>
   <tag></tag>
   <elementGuidId>00feb0da-6313-47e0-93c7-b4ef4e850dfa</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>i.ft-x.ng-tns-c133-2</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='sidebarClose']/i</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>4da11d34-ee84-4309-8849-6ba8da01c17d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ft-x ng-tns-c133-2</value>
      <webElementGuid>6c42df78-c122-454a-b903-64e1d6814286</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;sidebarClose&quot;)/i[@class=&quot;ft-x ng-tns-c133-2&quot;]</value>
      <webElementGuid>a485e94c-3875-46f3-b139-046817d6e6d4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='sidebarClose']/i</value>
      <webElementGuid>2980e25b-aef9-4982-8532-647123117355</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[3]/i</value>
      <webElementGuid>73e51ab3-ba39-4d81-96f9-940972ee8b0d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
