<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>tombolX_menu</name>
   <tag></tag>
   <elementGuidId>00feb0da-6313-47e0-93c7-b4ef4e850dfa</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='sidebarClose']/i</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>i.ft-x.ng-tns-c133-2</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;sidebarClose&quot;)/i[@class=&quot;ft-x ng-tns-c133-2&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>186c6c05-2445-40b7-8562-73e2dd3230c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>nav-close d-block d-lg-block d-xl-none ng-tns-c133-4</value>
      <webElementGuid>d23517f5-7fdf-45ad-b4f4-77fb8eae94cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;sidebarClose&quot;)/i[@class=&quot;ft-x ng-tns-c133-2&quot;]</value>
      <webElementGuid>40828bfa-22db-44a3-a031-3a2065ce6272</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='sidebarClose']/i</value>
      <webElementGuid>65887e52-4bbd-485a-8871-7b0394e90bae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[3]/i</value>
      <webElementGuid>00d0f2e6-119f-494a-9c1e-a80c0248660f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
