<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>DiskonUI</name>
   <tag></tag>
   <elementGuidId>ee51f2c9-7809-48cd-ab75-ff0e56eac7c7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;msxForm&quot;]/div[6]/div[1]/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;msxForm&quot;]/div[6]/div[1]/div</value>
      <webElementGuid>290aab42-fc58-4bd4-b459-f103c4f97e1b</webElementGuid>
   </webElementProperties>
</WebElementEntity>
