<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>modifyObject</name>
   <tag></tag>
   <elementGuidId>6b2bd8a1-6ab1-4c53-a32d-9f82eec70548</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value></value>
      <webElementGuid>bb70f15f-a4b5-45da-831e-225cefa3739f</webElementGuid>
   </webElementProperties>
</WebElementEntity>
