<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_WILLIS_ft-chevron-down</name>
   <tag></tag>
   <elementGuidId>c3e68df9-d634-465a-a516-eb7bb7a867af</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='dropdownBasic2']/div[2]/i</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>i.ft-chevron-down</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>452dcd19-2d9b-4684-8a57-cc981b625ea1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ft-chevron-down</value>
      <webElementGuid>bd831599-00df-4e91-b21a-b1af687d4ada</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dropdownBasic2&quot;)/div[2]/i[@class=&quot;ft-chevron-down&quot;]</value>
      <webElementGuid>10177ff5-920f-4b3a-9c36-972f158aeeef</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='dropdownBasic2']/div[2]/i</value>
      <webElementGuid>aa865bc0-bbd9-40d0-8a96-6e5f3c700ca4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/i</value>
      <webElementGuid>4b50b5fb-3bfc-430f-8ef5-37b8587e400c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
