<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__roleName</name>
   <tag></tag>
   <elementGuidId>2d0cb611-8733-4fb1-8ae8-eaff32c9233d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#roleName</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='roleName']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>36efe29e-46ba-4be1-9f0c-24e58164e19e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>931b0092-912a-452d-9252-f24f47fa1fe1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ng-untouched ng-pristine ng-invalid</value>
      <webElementGuid>37b3f31a-3eac-4254-bda3-ef0fdec6de75</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-name</name>
      <type>Main</type>
      <value>roleName</value>
      <webElementGuid>f9477f7f-9339-49d9-89c9-5c55c957dd5c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>roleName</value>
      <webElementGuid>27ddac80-415c-491f-a89c-f309312f5017</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter role name</value>
      <webElementGuid>c2261cd4-793a-48d1-bdd2-2167e4b1409e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>28e0a534-b81b-4503-8373-d6a29300c9cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;roleName&quot;)</value>
      <webElementGuid>2ef2001d-d188-4769-8405-038abe559e4f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='roleName']</value>
      <webElementGuid>5bc178ed-68fe-42b3-a58b-0c980030a09d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='msxForm']/div/div/app-question/app-text/fieldset/div/input</value>
      <webElementGuid>1ea30d98-f48f-4942-8be8-bf8721053450</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>f65588c8-1444-43c2-a5f5-4eaa8d4b787b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'roleName' and @placeholder = 'Enter role name']</value>
      <webElementGuid>64819b79-6cde-4e5b-8f29-423b4023025f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
