<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__jmlkupon</name>
   <tag></tag>
   <elementGuidId>322b1605-aff0-47af-925e-f8b9e8d1dd3b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#couponQty</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='couponQty']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a5c3e1ec-5623-47e9-b795-86fcbd91c819</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>tel</value>
      <webElementGuid>6a6b9346-c3b8-46c6-9a00-4608fa7e3d85</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>mask</name>
      <type>Main</type>
      <value>separator.0</value>
      <webElementGuid>492c553a-6030-4005-a09a-7e56b322cfaf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>thousandseparator</name>
      <type>Main</type>
      <value>.</value>
      <webElementGuid>df134019-7345-42dc-9815-83ee13878f48</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ng-untouched ng-pristine ng-valid</value>
      <webElementGuid>f9693d59-39ee-4315-81c3-ad5e4e4101b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-mask-expression</name>
      <type>Main</type>
      <value>separator.0</value>
      <webElementGuid>c103ae55-d201-42f6-815f-c7f67d19b511</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-thousand-separator</name>
      <type>Main</type>
      <value>.</value>
      <webElementGuid>ff7751f7-df12-46a5-b019-48a57560d23a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-name</name>
      <type>Main</type>
      <value>couponQty</value>
      <webElementGuid>ef5bc1be-8a4a-4692-8ab6-94c0a37c696d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>couponQty</value>
      <webElementGuid>32defc30-0bcd-4a4b-8a2b-edd33b906792</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>0c694fba-c4c7-4b14-9d34-47158d2c64a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>301c9336-b3f6-42a6-af85-e99adcdb16af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;couponQty&quot;)</value>
      <webElementGuid>03da42d9-02d1-4349-8a2e-52abf0b3fd57</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='couponQty']</value>
      <webElementGuid>1a4736a8-fb66-446b-907c-89d3ce010496</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/div/app-currency/fieldset/input</value>
      <webElementGuid>53c59387-c14e-462d-bdc2-6ad395be6608</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'tel' and @id = 'couponQty' and @placeholder = '1']</value>
      <webElementGuid>88334e51-bbf2-4a11-bd5f-52e2a793b0cc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
