<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__nilaikupon</name>
   <tag></tag>
   <elementGuidId>649498ba-f594-45e3-acf3-de5045e78189</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#couponAmount</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='couponAmount']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c5f83389-6e46-4ce6-b3cf-9c59439bed1c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>tel</value>
      <webElementGuid>97f19e75-e3f3-4e23-b63a-aafbe2adbf19</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>mask</name>
      <type>Main</type>
      <value>separator.0</value>
      <webElementGuid>4a95edbe-d59a-425f-9bfc-185e04d6b397</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>thousandseparator</name>
      <type>Main</type>
      <value>.</value>
      <webElementGuid>245889ae-6038-4ca6-9a66-e27b10b31180</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ng-untouched ng-pristine ng-invalid</value>
      <webElementGuid>4f49a26d-f3bd-4c60-b35e-7fcf887662fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-mask-expression</name>
      <type>Main</type>
      <value>separator.0</value>
      <webElementGuid>d29653e3-cc9f-4277-9add-9de4d5cd551d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-thousand-separator</name>
      <type>Main</type>
      <value>.</value>
      <webElementGuid>3a75529f-f12b-4a0f-b3d4-4c34952f7fbe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-name</name>
      <type>Main</type>
      <value>couponAmount</value>
      <webElementGuid>ae155e34-a784-4453-93da-348ccb8e2cde</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>couponAmount</value>
      <webElementGuid>89db4019-b32d-427d-9b49-7aa8bad2d157</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>931da1f4-522b-49cb-9147-ee307b1e0234</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>a3460ad5-1a18-4cad-9b40-cfd8b526ca12</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;couponAmount&quot;)</value>
      <webElementGuid>fd905567-5d9d-4e32-b686-814f359faa19</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='couponAmount']</value>
      <webElementGuid>ccb8462b-d9eb-4aba-b14c-c4c4b3016d78</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//fieldset/input</value>
      <webElementGuid>8038f4f5-abfd-4181-ab65-0cf7657782a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'tel' and @id = 'couponAmount' and @placeholder = '0']</value>
      <webElementGuid>728d052f-3129-4a60-921b-ed167080da1b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
