<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__couponStartDate</name>
   <tag></tag>
   <elementGuidId>c2693ddf-aa22-4672-b8ed-e74f62148f07</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#couponStartDate</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='couponStartDate']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>8513081a-226f-4211-b38c-6aa154449f83</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>c26d6944-fe9b-42f9-b933-712876ce758a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ng-untouched ng-pristine ng-invalid</value>
      <webElementGuid>484ab985-c8b9-41c5-83c8-d07d7466a58e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-name</name>
      <type>Main</type>
      <value>couponStartDate</value>
      <webElementGuid>51e2684b-fe0c-4a71-a01d-492ed63d53be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>couponStartDate</value>
      <webElementGuid>6c305e82-7bbc-4ead-b97f-39f9674ca7a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>yyyy-mm-dd</value>
      <webElementGuid>63f4645f-7e61-42a6-91fd-6210d1037a4d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;couponStartDate&quot;)</value>
      <webElementGuid>69b4110d-9c8a-4fca-b59b-a64cde00de1a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='couponStartDate']</value>
      <webElementGuid>b1077217-e263-4ea9-b0a8-2f2a5280989c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//app-date/fieldset/div/input</value>
      <webElementGuid>a962e82f-460d-4e95-aa63-eb3fd87f14d6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'couponStartDate' and @placeholder = 'yyyy-mm-dd']</value>
      <webElementGuid>cdd30206-69d2-4633-a3d8-b04e3e0618f8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
