<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__couponCode</name>
   <tag></tag>
   <elementGuidId>3c90d5fb-1689-4392-ae33-ed5357721f73</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#couponCode</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='couponCode']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b980ec38-967c-45bc-b525-d73219aae794</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>8c5d5331-a34b-41cb-bc8f-f15bc4d9f4ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ng-untouched ng-pristine ng-invalid</value>
      <webElementGuid>08afb3c0-55d6-484f-82ac-93c87bcf0b7a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-name</name>
      <type>Main</type>
      <value>couponCode</value>
      <webElementGuid>0290148d-ed6a-482b-95bd-6c26d164072b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>couponCode</value>
      <webElementGuid>3a171ed0-ed23-4ad7-b3b1-ac31d1dc25a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Ketik kode kupon di sini</value>
      <webElementGuid>9692e7a4-ba2d-42c7-8025-e2990bfab59c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>a18858fa-2802-4095-80ff-addd54c16f4f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;couponCode&quot;)</value>
      <webElementGuid>448ffc40-bd34-4985-ba58-8225c179d113</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='couponCode']</value>
      <webElementGuid>10174c27-1b5e-487a-b8fd-4c01fb1222fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//fieldset/div/input</value>
      <webElementGuid>8a2561a4-fec2-4ced-8929-c77822f3a694</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'couponCode' and @placeholder = 'Ketik kode kupon di sini']</value>
      <webElementGuid>d1070148-c29d-474e-9476-169c73a84e4e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
