<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>menu_Balance</name>
   <tag></tag>
   <elementGuidId>dbb06e5b-a471-4126-b1db-ff22054ed06c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@href = '/balance']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-parent</name>
      <type>Main</type>
      <value>Balance</value>
      <webElementGuid>214c3c9e-4036-4070-b19a-f62531569cda</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/balance</value>
      <webElementGuid>55a7b277-fa4b-4d49-b11b-94193a0e455d</webElementGuid>
   </webElementProperties>
</WebElementEntity>
