<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Simpan</name>
   <tag></tag>
   <elementGuidId>ae3ae6e9-a456-4a7c-88b5-4599c728554f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>/html/body/app-root/app-full-layout/div/div[2]/div/div[2]/app-balance-charge/div[2]/div/div/div/div/div/div/button[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/app-root/app-full-layout/div/div[2]/div/div[2]/app-balance-charge/div[2]/div/div/div/div/div/div/button[2]</value>
      <webElementGuid>fa191189-cf2a-418e-88b8-c3b8cef2dfa2</webElementGuid>
   </webElementProperties>
</WebElementEntity>
