<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>namaTenant</name>
   <tag></tag>
   <elementGuidId>a000f8dc-bbe6-4c63-8837-538667540f5a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value></value>
      <webElementGuid>080fac3d-97d3-40de-afb2-0ad73e2508c7</webElementGuid>
   </webElementProperties>
</WebElementEntity>
