<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Unduh Excel Set Ulang Cari</name>
   <tag></tag>
   <elementGuidId>dac2892c-bbd7-4600-b4e2-6b183896224e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.col-12.text-right</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='searchForm']/div[2]/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>60f4aa02-a352-4683-98f8-8101644df18a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>col-12 text-right</value>
      <webElementGuid>0ac8eab0-8c6e-4e3a-82dc-e8386cb8410a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Unduh Excel Set Ulang Cari</value>
      <webElementGuid>ea89da4c-4f71-404c-81e4-261876988d13</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;searchForm&quot;)/div[@class=&quot;row&quot;]/div[@class=&quot;col-12 text-right&quot;]</value>
      <webElementGuid>edf698c0-5a4b-4f53-acb5-ad68d005e8c7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='searchForm']/div[2]/div</value>
      <webElementGuid>4c692bf4-cf16-49f6-ae2e-1fd679bab8a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='All'])[3]/following::div[3]</value>
      <webElementGuid>489b72af-1e25-4099-948a-f87da6c9b29a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select Process Result'])[1]/following::div[4]</value>
      <webElementGuid>b80067cf-4567-42f6-a801-2a2f485890b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div[2]/div</value>
      <webElementGuid>a177f889-3034-4c62-9d05-f1cf3a024d98</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = ' Unduh Excel Set Ulang Cari' or . = ' Unduh Excel Set Ulang Cari')]</value>
      <webElementGuid>15f29c7e-d968-433a-8723-f42f59a88f67</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
