<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Tanggal Transaksi Dari_transactionDateStart</name>
   <tag></tag>
   <elementGuidId>115650c0-9f64-478c-9c56-dbc4b30dd7bf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#transactionDateStart</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='transactionDateStart']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>3c570878-730a-4d7e-9243-a5014be173ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>c207ecba-7b9a-4f60-a1ee-f76e98aca918</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ng-untouched ng-pristine ng-invalid</value>
      <webElementGuid>c5a18cbc-4414-4d7f-9578-71fafcb3f0ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-name</name>
      <type>Main</type>
      <value>transactionDateStart</value>
      <webElementGuid>947b0930-99a9-46e5-a2d2-941cc705c77b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>transactionDateStart</value>
      <webElementGuid>7f27fcc2-eb9e-45e5-8be3-38fae0450c01</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>yyyy-mm-dd</value>
      <webElementGuid>6d8c1a34-cecd-4541-8d34-6a614960f101</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;transactionDateStart&quot;)</value>
      <webElementGuid>a2d53906-6ddd-410b-83ee-2647f6de91ea</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='transactionDateStart']</value>
      <webElementGuid>19164c55-2e95-4b39-b704-8e9279d8b903</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='searchForm']/div/div[5]/app-question/app-date/div/div[2]/div/input</value>
      <webElementGuid>e910c656-b099-4ccc-8dd0-9bd66a18f9bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//app-date/div/div[2]/div/input</value>
      <webElementGuid>a4ec1474-6b72-4907-81fe-5b7d55273c88</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'transactionDateStart' and @placeholder = 'yyyy-mm-dd']</value>
      <webElementGuid>2cffc63b-c207-4ce4-842d-3df1317587a5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
