<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>lastPage</name>
   <tag></tag>
   <elementGuidId>bc14596b-2662-46f5-a9bc-e04dfa56cc08</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value></value>
      <webElementGuid>a04cd590-ec67-4de1-8b99-b8e986f5ea8b</webElementGuid>
   </webElementProperties>
</WebElementEntity>
