<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>modifybuttonpage</name>
   <tag></tag>
   <elementGuidId>7f88116d-b945-486e-9bd5-d2856759ee9e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value></value>
      <webElementGuid>b35a71e3-cfa6-490c-8804-b7e414122a74</webElementGuid>
   </webElementProperties>
</WebElementEntity>
