<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>jumlahDetail</name>
   <tag></tag>
   <elementGuidId>cfe178ea-7946-4abf-aacb-30088abcc09b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value></value>
      <webElementGuid>9c2852a0-a839-4e86-a46d-b5391e3b3371</webElementGuid>
   </webElementProperties>
</WebElementEntity>
