<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>metodeTranx</name>
   <tag></tag>
   <elementGuidId>83ba3b74-f08a-405c-b655-e62b1b480cea</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value></value>
      <webElementGuid>35f5d90e-2d4b-49ef-97ed-863e5510cc5b</webElementGuid>
   </webElementProperties>
</WebElementEntity>
