<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>noTranx</name>
   <tag></tag>
   <elementGuidId>4619d061-b66f-419c-abec-07e3be4166c3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value></value>
      <webElementGuid>8468a1fa-b489-47c6-94a0-7a097f142c64</webElementGuid>
   </webElementProperties>
</WebElementEntity>
