<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>statusTranx</name>
   <tag></tag>
   <elementGuidId>194d5470-6884-4d88-82fa-7c5b74651b4b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value></value>
      <webElementGuid>7631c3de-b2c8-41c6-8ba4-b5ab05a5ea30</webElementGuid>
   </webElementProperties>
</WebElementEntity>
