<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>tglTranx</name>
   <tag></tag>
   <elementGuidId>3fd9b190-9ec3-4287-9ebf-8cb6250a93a1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value></value>
      <webElementGuid>7c18ef0a-073d-46a6-891c-a41984386233</webElementGuid>
   </webElementProperties>
</WebElementEntity>
