<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Status API Key Enter activation statusI_e6aed9</name>
   <tag></tag>
   <elementGuidId>911c411e-f6a3-44c4-b34d-3f795917de03</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='msxForm']/div/div[2]/app-question/app-select/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.form-group.ng-star-inserted.ng-dirty.ng-invalid.ng-touched</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>0b840e4a-26e2-4a9c-8f57-8ba7fd546ffc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-group ng-star-inserted ng-dirty ng-invalid ng-touched</value>
      <webElementGuid>34e0f76f-439f-450c-9935-0c1040b82b42</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-form</name>
      <type>Main</type>
      <value>[object Object]</value>
      <webElementGuid>7264c5a2-0695-402f-ba60-03b080680538</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Status API Key *Enter activation status×Inactive×ActiveInactive</value>
      <webElementGuid>5f72eb5e-7465-484c-9e45-e3e6188fe869</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;msxForm&quot;)/div[@class=&quot;row&quot;]/div[@class=&quot;col-12 ng-star-inserted&quot;]/app-question[1]/app-select[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;form-group ng-star-inserted ng-dirty ng-invalid ng-touched&quot;]</value>
      <webElementGuid>e81e91a2-ea2e-462d-b05c-c58882d8f6bb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='msxForm']/div/div[2]/app-question/app-select/div</value>
      <webElementGuid>e12821e0-b525-4b4d-a18b-f450c6648a53</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nama Api Key harus di isi.'])[1]/following::div[3]</value>
      <webElementGuid>96afb05e-f23f-4064-aef1-74a0ffcc243b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[1]/following::div[6]</value>
      <webElementGuid>59100266-d584-464f-a495-960f6cfe76cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//app-select/div</value>
      <webElementGuid>02212e27-ff85-44b6-92f4-083cb04bcb06</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Status API Key *Enter activation status×Inactive×ActiveInactive' or . = 'Status API Key *Enter activation status×Inactive×ActiveInactive')]</value>
      <webElementGuid>ee3b5068-a359-497c-9a4b-77942062e0f0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
