<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>AcceptTnC</name>
   <tag></tag>
   <elementGuidId>7fa2ce8f-ef3b-4aed-b970-cd2e259e733a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//section[@id='login']/div/div[2]/div/mat-tab-group/div/mat-tab-body[2]/div/form/div[6]/div/div/label</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//section[@id='login']/div/div[2]/div/mat-tab-group/div/mat-tab-body[2]/div/form/div[6]/div/div/label</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//section[@id='login']/div/div[2]/div/mat-tab-group/div/mat-tab-body[2]/div/form/div[6]/div/div/label</value>
      <webElementGuid>a0836375-d100-4aea-9804-d0a877c1a4ff</webElementGuid>
   </webElementProperties>
</WebElementEntity>
