<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>check_Recaptcha</name>
   <tag></tag>
   <elementGuidId>470e3279-8c0e-4e15-903f-ca5dfafd292a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;mat-tab-content-0-0&quot;]/div/form/div[8]/div/div[2]/ngx-recaptcha2/div/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.recaptcha-checkbox-border</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;mat-tab-content-0-0&quot;]/div/form/div[8]/div/div[2]/ngx-recaptcha2/div/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>41dc2a2f-91e6-4052-9d79-e88dc951622d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>recaptcha-checkbox-border</value>
      <webElementGuid>798630e5-9572-43c3-9023-ad3404494f36</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>presentation</value>
      <webElementGuid>c9cbd266-d2e4-4bda-8ebc-1b4d14b6a98f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;mat-tab-content-0-0&quot;]/div/form/div[8]/div/div[2]/ngx-recaptcha2/div/div</value>
      <webElementGuid>469eb711-7d8e-4720-931b-cef62db12280</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='recaptcha-anchor']/div</value>
      <webElementGuid>a05e868c-9aab-4c9f-bd7f-597dd0b4919f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/div</value>
      <webElementGuid>643ea7dc-c7ec-42cc-b19f-aecfbc13d2b1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
