<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_Lupa Kata Sandi_a-fqiryovxupng</name>
   <tag></tag>
   <elementGuidId>85460542-c695-430d-9e72-9d52fae60047</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@name='a-fqiryovxupng']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>iframe[name=&quot;a-fqiryovxupng&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>5a08ac36-baff-403a-ad6a-ddc968dc5818</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>reCAPTCHA</value>
      <webElementGuid>9e6a6e9d-d300-47ab-a8c7-a946ee5420d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://www.google.com/recaptcha/api2/anchor?ar=1&amp;k=6LcDnrckAAAAAOvOHY_-Rd-L-T6KyqwMtloQn_61&amp;co=aHR0cDovL2dka3dlYnN2cjo0MTAw&amp;hl=id&amp;type=image&amp;v=8G7OPK94bhCRbT0VqyEVpQNj&amp;theme=light&amp;size=normal&amp;cb=migignywtbr</value>
      <webElementGuid>1d71a668-61a6-4cb4-8a84-cb4ded22b868</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>304</value>
      <webElementGuid>e0a07890-55ae-4b7a-8dde-342ea8c5c254</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>78</value>
      <webElementGuid>e401d801-30af-4c8d-9f24-f751c8235aca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>presentation</value>
      <webElementGuid>509fcea6-ac26-4e28-a8ea-0e895beb9eb3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>a-fqiryovxupng</value>
      <webElementGuid>bac7bf72-f709-4b35-b282-2b2133a8ffe4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>531151b2-3b29-4ac8-afd7-d8b400d2b228</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scrolling</name>
      <type>Main</type>
      <value>no</value>
      <webElementGuid>56651c69-c46b-4ea8-aed4-81f2dde4929b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>sandbox</name>
      <type>Main</type>
      <value>allow-forms allow-popups allow-same-origin allow-scripts allow-top-navigation allow-modals allow-popups-to-escape-sandbox</value>
      <webElementGuid>8a377fd9-3c8a-4243-90be-1d707716cfce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ngx_captcha_id_5062&quot;)/div[1]/div[1]/iframe[1]</value>
      <webElementGuid>4b4478b1-1b29-4d5f-8a4e-d654287490bc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@name='a-fqiryovxupng']</value>
      <webElementGuid>b8a9f163-c93f-43eb-b0aa-5c835bad7a34</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ngx_captcha_id_5062']/div/div/iframe</value>
      <webElementGuid>047622ce-24a2-410d-ad2b-f13a4c66aa5b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div/iframe</value>
      <webElementGuid>c913be6d-2696-4354-9a22-ed7d39f829bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@title = 'reCAPTCHA' and @src = 'https://www.google.com/recaptcha/api2/anchor?ar=1&amp;k=6LcDnrckAAAAAOvOHY_-Rd-L-T6KyqwMtloQn_61&amp;co=aHR0cDovL2dka3dlYnN2cjo0MTAw&amp;hl=id&amp;type=image&amp;v=8G7OPK94bhCRbT0VqyEVpQNj&amp;theme=light&amp;size=normal&amp;cb=migignywtbr' and @name = 'a-fqiryovxupng']</value>
      <webElementGuid>043365d7-0c6a-40a8-b01c-ffe0f50e2081</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
