<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_Lupa Kata Sandi_a-xt42qnpqup86</name>
   <tag></tag>
   <elementGuidId>fca835ae-dce2-444e-8eee-61369854ca78</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@name='a-xt42qnpqup86']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>iframe[name=&quot;a-xt42qnpqup86&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>36eabb5d-d382-4ad3-b19b-9f26c43df2d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>reCAPTCHA</value>
      <webElementGuid>ab8faf96-4555-4213-b38c-2448955227a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://www.google.com/recaptcha/api2/anchor?ar=1&amp;k=6LcDnrckAAAAAOvOHY_-Rd-L-T6KyqwMtloQn_61&amp;co=aHR0cDovL2dka3dlYnN2cjo0MTAw&amp;hl=id&amp;type=image&amp;v=MuIyr8Ej74CrXhJDQy37RPBe&amp;theme=light&amp;size=normal&amp;cb=n2o15hf7lnme</value>
      <webElementGuid>49a5b090-ce4d-4e7c-a928-27593b6bb11e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>304</value>
      <webElementGuid>df9c7462-58b0-4332-b9dc-2369404e42da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>78</value>
      <webElementGuid>6b5b6f1b-70e6-4e86-8dac-5d5caaff7112</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>presentation</value>
      <webElementGuid>d74f086c-f783-44db-b1f1-2a40dbc7bd79</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>a-xt42qnpqup86</value>
      <webElementGuid>e9de5be8-59d8-40eb-a1a3-c2560fc375d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>47888f9e-d53a-42b1-a6ab-13ce1e6e2d98</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scrolling</name>
      <type>Main</type>
      <value>no</value>
      <webElementGuid>aba65034-2a21-47ec-b784-9137b25228e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>sandbox</name>
      <type>Main</type>
      <value>allow-forms allow-popups allow-same-origin allow-scripts allow-top-navigation allow-modals allow-popups-to-escape-sandbox</value>
      <webElementGuid>bf62b51b-fb05-4a15-8d7d-f417dfee147b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ngx_captcha_id_1741&quot;)/div[1]/div[1]/iframe[1]</value>
      <webElementGuid>c21d9563-6ae9-4183-8dc7-a834b2c90572</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@name='a-xt42qnpqup86']</value>
      <webElementGuid>42563a9a-3932-40c9-be8c-594bb6083e3d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ngx_captcha_id_1741']/div/div/iframe</value>
      <webElementGuid>11f6bffc-d737-4b63-bfa2-9d9975b86576</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div/iframe</value>
      <webElementGuid>01e0032c-9629-4571-8aed-1531420e63b5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@title = 'reCAPTCHA' and @src = 'https://www.google.com/recaptcha/api2/anchor?ar=1&amp;k=6LcDnrckAAAAAOvOHY_-Rd-L-T6KyqwMtloQn_61&amp;co=aHR0cDovL2dka3dlYnN2cjo0MTAw&amp;hl=id&amp;type=image&amp;v=MuIyr8Ej74CrXhJDQy37RPBe&amp;theme=light&amp;size=normal&amp;cb=n2o15hf7lnme' and @name = 'a-xt42qnpqup86']</value>
      <webElementGuid>457fbfa5-5a27-427f-a07f-e45eaddd965a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
