<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>containerForm</name>
   <tag></tag>
   <elementGuidId>b1ac43d1-ecb9-4bc8-994f-292c25e76291</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.row.match-height > div.col-6</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>/html/body/app-root/app-full-layout/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>9ca5c8ac-72c3-4010-8224-118130d4a8c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>col-6</value>
      <webElementGuid>91475020-1112-4ca3-91d7-f2c459cc182b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>TenantPilih tenant×Pilih Tenant×VendorPilih vendor×Pilih Vendor×Tipe SaldoPilih Tipe Saldo×Pilih Tipe Saldo×Tambah SaldoNomor TagihanCatatanTanggal PembelianBatalLanjut</value>
      <webElementGuid>17c6ce82-b196-453c-bb89-cd45adb4204f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;vertical-layout menu-hide navbar-static pace-done&quot;]/app-root[1]/app-full-layout[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;wrapper&quot;]/div[@class=&quot;main-panel&quot;]/div[@class=&quot;main-content&quot;]/div[@class=&quot;content-wrapper&quot;]/app-topup-balance[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;row match-height&quot;]/div[@class=&quot;col-6&quot;]</value>
      <webElementGuid>af56bd7a-da37-4880-90c8-6ee8fd7710cb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Isi Saldo'])[2]/following::div[2]</value>
      <webElementGuid>940680ec-38a8-4bc5-a23b-903613ca293d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tenant'])[1]/following::div[13]</value>
      <webElementGuid>35ddcac2-f8a2-40ea-8561-d1aa8a27d0be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//app-topup-balance/div[2]/div</value>
      <webElementGuid>e2b9f1f8-6c88-4482-bca6-3c8eef5f4d7d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'TenantPilih tenant×Pilih Tenant×VendorPilih vendor×Pilih Vendor×Tipe SaldoPilih Tipe Saldo×Pilih Tipe Saldo×Tambah SaldoNomor TagihanCatatanTanggal PembelianBatalLanjut' or . = 'TenantPilih tenant×Pilih Tenant×VendorPilih vendor×Pilih Vendor×Tipe SaldoPilih Tipe Saldo×Pilih Tipe Saldo×Tambah SaldoNomor TagihanCatatanTanggal PembelianBatalLanjut')]</value>
      <webElementGuid>e697a2c5-92e7-4986-bf92-c845dc035942</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
