<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_IDR</name>
   <tag></tag>
   <elementGuidId>9b658eae-1ad9-47e3-8585-7ce6ff2fff84</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='a5f26759fe4b-1']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#a5f26759fe4b-1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>9e1143de-1ebf-4e8d-8526-207bbf405989</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-option ng-star-inserted ng-option-marked</value>
      <webElementGuid>bdfa95e5-5f07-4098-a957-a07d7a7950a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>5c69b693-4bfb-4b50-a5ba-8bb38724f9cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>a5f26759fe4b-1</value>
      <webElementGuid>651559b9-538b-454e-881c-6b1445b29a59</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>IDR</value>
      <webElementGuid>7ae1ad43-4952-4cea-88d9-671e0164d185</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;a5f26759fe4b-1&quot;)</value>
      <webElementGuid>d9d9fbc8-f9a4-4dd4-a227-4f06afae0057</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='a5f26759fe4b-1']</value>
      <webElementGuid>71e65d23-55b8-42fa-93f8-9399cfadb847</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ng-dropdown-panel[@id='a5f26759fe4b']/div/div[2]/div[2]</value>
      <webElementGuid>bac2b4db-6b77-4c53-ab69-089dcec87a67</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pilih Tipe Saldo'])[2]/following::div[1]</value>
      <webElementGuid>2b56cd6c-b59e-4637-bfd1-f4ebe98594c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pilih Tipe Saldo'])[1]/following::div[6]</value>
      <webElementGuid>34d52d06-cc0b-42e2-ba7c-7001474455af</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='OCR BPKB'])[1]/preceding::div[1]</value>
      <webElementGuid>26124398-348d-4d0c-9853-e926762a9542</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[2]/div[2]</value>
      <webElementGuid>66894f2b-1253-479c-873e-863b8fc90f82</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'a5f26759fe4b-1' and (text() = 'IDR' or . = 'IDR')]</value>
      <webElementGuid>fe90dbcd-671e-41be-8e15-d687e5c88540</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
