<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_QUICKSILVER</name>
   <tag></tag>
   <elementGuidId>11de3b2e-7add-42ce-a14f-f52a9b4e7f79</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='af715cc6c9df-45']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#af715cc6c9df-45</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>b58f8a08-a351-40fe-81d3-57d374efec87</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-option ng-star-inserted ng-option-marked</value>
      <webElementGuid>9f233f3c-146f-4295-be64-ac88b0726db5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>961d1dc3-0c0a-484f-8075-13fb3f564f68</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>af715cc6c9df-45</value>
      <webElementGuid>fd9622e8-5caf-422b-8d27-d7bd3cfd6563</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>QUICKSILVER</value>
      <webElementGuid>cde366df-a83d-4de8-aa95-92375cc6577c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;af715cc6c9df-45&quot;)</value>
      <webElementGuid>56d04d68-6f2a-4915-9949-3cb75f305a34</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='af715cc6c9df-45']</value>
      <webElementGuid>6c0bbe12-f486-40a0-b8d6-0596cf08cc5c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ng-dropdown-panel[@id='af715cc6c9df']/div/div[2]/div[46]</value>
      <webElementGuid>bef66855-3946-4617-b8af-d82155bdc361</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PT A'])[1]/following::div[1]</value>
      <webElementGuid>839fecfc-0d28-4452-8243-617647146e25</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PT WILLIS'])[1]/following::div[2]</value>
      <webElementGuid>fd55b402-1400-4df3-884a-df32778b712b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sarana Global Finance'])[1]/preceding::div[1]</value>
      <webElementGuid>f1ecfc04-4e9b-4d16-81f3-1b7e5206d649</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[46]</value>
      <webElementGuid>f652700c-661f-4603-8d8b-eea5a464913a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'af715cc6c9df-45' and (text() = 'QUICKSILVER' or . = 'QUICKSILVER')]</value>
      <webElementGuid>8a080194-6707-4f0c-a34e-1043ceff186f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
