<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_ADINS</name>
   <tag></tag>
   <elementGuidId>b4da8b98-cd24-49bb-b084-5370588222e6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='a9e1e8b65798-1']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#a9e1e8b65798-1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>2730bb83-1985-4ea1-88ae-d94ee117f7e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-option ng-option-selected ng-star-inserted ng-option-marked</value>
      <webElementGuid>d16868f3-5883-4d02-8e11-c4114bb3e464</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>03ba0f8b-4eba-45bf-8895-602afd75188f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>f6c4cb4a-8c26-463f-986e-f672a15d16a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>a9e1e8b65798-1</value>
      <webElementGuid>7621c735-4434-4071-a333-6d75874dd576</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>ADINS</value>
      <webElementGuid>b425ee0e-e2d1-4231-8d95-ea3bc41a2939</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;a9e1e8b65798-1&quot;)</value>
      <webElementGuid>8020624f-a1fe-41d9-b946-8bc093e24be9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='a9e1e8b65798-1']</value>
      <webElementGuid>6464c13b-7eb0-4462-ae9e-17bb97d834e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ng-dropdown-panel[@id='a9e1e8b65798']/div/div[2]/div[2]</value>
      <webElementGuid>3e71b9d8-945c-4e83-b1ce-1d4b78351884</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pilih Vendor'])[1]/following::div[1]</value>
      <webElementGuid>832b0280-2d5f-48f5-a7d2-4baacef4dc00</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ADINS'])[1]/following::div[6]</value>
      <webElementGuid>2f3f46e5-c336-4d60-9a6c-90b89006cd47</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tipe Saldo'])[1]/preceding::div[1]</value>
      <webElementGuid>bdddce9b-6edb-4c38-8e2d-d43f34f849ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[2]/div[2]</value>
      <webElementGuid>71f076ba-23f6-4a33-ae63-4f0f9218200b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'a9e1e8b65798-1' and (text() = 'ADINS' or . = 'ADINS')]</value>
      <webElementGuid>38bbcdae-771e-4034-80f5-ed882ada3818</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
