<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>fieldset_Tambah Saldo</name>
   <tag></tag>
   <elementGuidId>7b1f9ea0-66ac-4c14-a34c-544e8ed1caca</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='xForm']/div/div[4]/app-currency/fieldset</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>fieldset.form-group.ng-invalid.ng-star-inserted.ng-touched.ng-dirty</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>fieldset</value>
      <webElementGuid>8a4c4395-2b29-4763-8682-aef43f837e8c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-group ng-invalid ng-star-inserted ng-touched ng-dirty</value>
      <webElementGuid>d0d15b52-a220-4163-ba68-054dcbd3d9b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Tambah Saldo</value>
      <webElementGuid>355bbb93-fc4d-42f8-92fd-d54d2e0f7d9e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;xForm&quot;)/div[@class=&quot;row&quot;]/div[@class=&quot;col-12&quot;]/app-currency[1]/fieldset[@class=&quot;form-group ng-invalid ng-star-inserted ng-touched ng-dirty&quot;]</value>
      <webElementGuid>f8c82989-6a30-4555-8ecc-a4bcb45d0d50</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='xForm']/div/div[4]/app-currency/fieldset</value>
      <webElementGuid>53a78aba-f87d-40bc-bd5d-e3836a96b898</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='IDR'])[1]/following::fieldset[1]</value>
      <webElementGuid>9e0be7b6-0f91-4df4-a144-e361b8f9b7d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pilih Tipe Saldo'])[1]/following::fieldset[1]</value>
      <webElementGuid>cb619ff3-54a1-4295-96dc-7b3dfcb70d43</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nomor Tagihan'])[1]/preceding::fieldset[1]</value>
      <webElementGuid>90a8f089-0040-4cc8-b295-c86c48f7f83a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//fieldset</value>
      <webElementGuid>32c73a3b-457f-4d4c-acc9-ee2fac39e02d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//fieldset[(text() = 'Tambah Saldo' or . = 'Tambah Saldo')]</value>
      <webElementGuid>10aefc71-f252-4e53-84f6-eb3cb9eac2e2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
