<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Nomor Tagihan_refNo</name>
   <tag></tag>
   <elementGuidId>e6798a32-916f-4ca9-89b1-7992bfcf808d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='refNo']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#refNo</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b6f765c0-387c-4e51-b551-a5161daf3097</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>65c4878a-d2b9-4af0-b83b-39d7d769bf6b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ng-untouched ng-pristine ng-invalid</value>
      <webElementGuid>ad639663-1f54-485e-9d7f-150d3ce70baf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>refNo</value>
      <webElementGuid>29077e84-1c7e-44f7-89ac-7a7f909fd8f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Tulis nomor tagihan</value>
      <webElementGuid>c2695e2c-e058-4ea1-a7da-6a6f9f040947</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>100</value>
      <webElementGuid>47c5c6ac-49fe-457e-a2d6-f742479fba31</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;refNo&quot;)</value>
      <webElementGuid>e0260432-6389-4b6e-a983-cfb59a2604cb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='refNo']</value>
      <webElementGuid>524a487b-7ff5-4e72-b905-f14be2ac430c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='xForm']/div/div[5]/app-text/fieldset/div/input</value>
      <webElementGuid>67ecae29-7f37-4ea0-9892-2819f660714f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//fieldset/div/input</value>
      <webElementGuid>8d26fa84-c6b8-40e5-a7b4-16d9d94b5d9d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'refNo' and @placeholder = 'Tulis nomor tagihan']</value>
      <webElementGuid>fb610f69-5964-4cfc-882d-ba9dc923d8dd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
