<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>TenantList</name>
   <tag></tag>
   <elementGuidId>b4277e6b-c34c-495a-aaaa-1ed3d1e71800</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value></value>
      <webElementGuid>bc2dc19c-7f57-4d46-8422-39dddfda7e1b</webElementGuid>
   </webElementProperties>
</WebElementEntity>
