<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>TipeSaldoList</name>
   <tag></tag>
   <elementGuidId>6f401695-7838-4f23-9500-cc9e83b13f6e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value></value>
      <webElementGuid>870fc319-ce55-45df-aa78-62ccfc9f10d6</webElementGuid>
   </webElementProperties>
</WebElementEntity>
