<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__CouponStartDate</name>
   <tag></tag>
   <elementGuidId>5f268c88-bda8-4a65-a0bc-7d3e8153ded3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#CouponStartDate</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='CouponStartDate']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a46dafde-f24b-4610-856c-d31d4d6649c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>56afb0c6-364b-474b-94ac-24d53f4cc0a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ng-untouched ng-pristine ng-invalid</value>
      <webElementGuid>61216e9d-2e79-428d-bd4c-635da8d1d3f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-name</name>
      <type>Main</type>
      <value>CouponStartDate</value>
      <webElementGuid>f59b2874-19c6-489c-80bd-4038b23370c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>CouponStartDate</value>
      <webElementGuid>1ace3aa8-aeff-496e-a752-82d6ca14b409</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>yyyy-mm-dd</value>
      <webElementGuid>4d849ff1-0a27-4778-9119-66391b19be86</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;CouponStartDate&quot;)</value>
      <webElementGuid>6df32d05-5f3e-4873-b25d-7780f62fa416</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='CouponStartDate']</value>
      <webElementGuid>5744ff7f-94ff-4e38-93bb-b4e18ffed71e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//app-date/fieldset/div/input</value>
      <webElementGuid>be244b8e-1adb-4c5c-a341-47ccc5ca7029</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'CouponStartDate' and @placeholder = 'yyyy-mm-dd']</value>
      <webElementGuid>5ceeeb0c-892a-4acc-97c8-b090a33cd791</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
