<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__minimumpayment</name>
   <tag></tag>
   <elementGuidId>56a8cfc9-a680-49ec-ad93-08d7a30a1995</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='MinimumPayment']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#MinimumPayment</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d05c269c-58f0-48e6-a635-f0f0d3d3c91e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>tel</value>
      <webElementGuid>8bf28dd2-8d86-4560-91bb-91531e2ac03e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>mask</name>
      <type>Main</type>
      <value>separator.0</value>
      <webElementGuid>d487f3bc-14af-4e57-b204-ae3337eeb563</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>thousandseparator</name>
      <type>Main</type>
      <value>.</value>
      <webElementGuid>ae21789c-8cf9-41a1-b7a7-f34726077ef4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ng-untouched ng-pristine ng-valid</value>
      <webElementGuid>c5e0cff6-795f-45d6-b74e-0383c93f10f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-mask-expression</name>
      <type>Main</type>
      <value>separator.0</value>
      <webElementGuid>91673dbf-c9db-4bb5-b95f-fc7658313d97</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-thousand-separator</name>
      <type>Main</type>
      <value>.</value>
      <webElementGuid>fd08df9e-7b74-42d0-8f1a-b160c38ae5a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-name</name>
      <type>Main</type>
      <value>MinimumPayment</value>
      <webElementGuid>a1f5be31-b8af-4050-ad74-0d9c413faefb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>MinimumPayment</value>
      <webElementGuid>e027f9fb-2fbf-4e73-9776-5367893aaff8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Ketik minimal pembayaran di sini</value>
      <webElementGuid>4e722f1e-035f-4dec-80bb-8237f2b5797a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>8c63aba5-2342-43f5-8324-d01daa3760dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;MinimumPayment&quot;)</value>
      <webElementGuid>771426c7-1754-4fd5-8850-61936848f621</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='MinimumPayment']</value>
      <webElementGuid>d1dff8c3-505e-4bb3-a98d-907d078394a0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[9]/div/app-currency/fieldset/input</value>
      <webElementGuid>00340b7b-1672-4bd9-9576-0660a94d95bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'tel' and @id = 'MinimumPayment' and @placeholder = 'Ketik minimal pembayaran di sini']</value>
      <webElementGuid>eb63e1f3-5bfb-40f6-a2e6-c3c018ef7e5a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
