<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__CouponStartDate</name>
   <tag></tag>
   <elementGuidId>5f268c88-bda8-4a65-a0bc-7d3e8153ded3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#CouponStartDate</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='CouponStartDate']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>93421644-099f-4187-b00c-b3ee70039a1b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>d47ef977-8039-435b-bfce-94690b3aa3bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ng-untouched ng-pristine ng-invalid</value>
      <webElementGuid>0ac36034-9648-4380-9224-2e0d39a63404</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-name</name>
      <type>Main</type>
      <value>CouponStartDate</value>
      <webElementGuid>9dd3a9da-d55f-4587-91b5-8210b0e24524</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>CouponStartDate</value>
      <webElementGuid>b74238de-af35-40fc-b7a2-ae2bfeddf634</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>yyyy-mm-dd</value>
      <webElementGuid>9833ea4e-e268-43c9-b056-e1665d54aa44</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;CouponStartDate&quot;)</value>
      <webElementGuid>7fd7116b-b3df-4799-934a-e9f7efd6f914</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='CouponStartDate']</value>
      <webElementGuid>e40b658a-8ee4-4510-a98e-dda760191d5d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//app-date/fieldset/div/input</value>
      <webElementGuid>f61be0c1-f8bb-4d8c-ac7a-a89170c164f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'CouponStartDate' and @placeholder = 'yyyy-mm-dd']</value>
      <webElementGuid>7362d044-7730-4938-b7d7-ed48ffc14ba9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
