<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__CouponCode</name>
   <tag></tag>
   <elementGuidId>f6610053-bd17-43a6-8b4e-544313b6c178</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#CouponCode</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='CouponCode']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e6d84833-d97a-40bf-870f-b64cff40c32b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>109ff561-7bd7-4f96-8f02-a56cc507fab1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ng-untouched ng-pristine ng-valid</value>
      <webElementGuid>c03ef571-9de8-462b-a670-3a2aa605816e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-name</name>
      <type>Main</type>
      <value>CouponCode</value>
      <webElementGuid>877cc00e-7592-473f-adc3-25da847be540</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>CouponCode</value>
      <webElementGuid>5e082cef-946d-421d-b6f2-42a6230805ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Ketik kode kupon di sini</value>
      <webElementGuid>733b6621-e96a-4550-9008-daac0a8716c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>bb053390-e730-40be-82bb-dfdf50af7ec3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;CouponCode&quot;)</value>
      <webElementGuid>7de3bd6b-2ce6-4a58-8b6b-e77c5f0da99a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='CouponCode']</value>
      <webElementGuid>19c7779c-f54f-4d8d-b49e-1b9550a3295c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//fieldset/div/input</value>
      <webElementGuid>273079bd-bbf1-400a-a591-ec9a35b65a02</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'CouponCode' and @placeholder = 'Ketik kode kupon di sini']</value>
      <webElementGuid>43867b95-c2c8-4f58-8457-9d0156f71147</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
