<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>dropdownProfile</name>
   <tag></tag>
   <elementGuidId>a0648640-dffa-444e-9eff-2f96520b6338</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>i.ft-chevron-down</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='dropdownBasic2']/div[2]/i</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>324c61f7-39b4-4c0a-9fd7-b021ce58ed62</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ft-chevron-down</value>
      <webElementGuid>37112c81-6389-4626-83dc-db5d837080b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dropdownBasic2&quot;)/div[2]/i[@class=&quot;ft-chevron-down&quot;]</value>
      <webElementGuid>1e8e7617-a70e-426c-9579-f2b69ed615c8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='dropdownBasic2']/div[2]/i</value>
      <webElementGuid>25a5b55b-1e5b-42cd-8b8a-81bb59086a89</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/i</value>
      <webElementGuid>f0c83c27-040f-4a59-9754-e3d4a729a257</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
