<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Baru</name>
   <tag></tag>
   <elementGuidId>781d0ab5-5ce9-4748-89ec-007d405d4c87</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.msx-action.btn.btn-primary.ng-star-inserted</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[contains(text(),'Baru')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>59691a86-0ef5-4f2f-a6bc-2fd667b9c36f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>msx-action btn btn-primary ng-star-inserted</value>
      <webElementGuid>f72deaa2-8fd5-4b43-9856-319c8acae422</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-ng-class</name>
      <type>Main</type>
      <value>btn btn-primary</value>
      <webElementGuid>915156f7-84d1-451a-b5d7-b1e5562b1727</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Baru</value>
      <webElementGuid>183c0408-2e23-4378-a3b5-c51ad5eafc47</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;vertical-layout menu-hide navbar-static pace-done pace-done&quot;]/app-root[1]/app-full-layout[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;wrapper&quot;]/div[@class=&quot;main-panel&quot;]/div[@class=&quot;main-content&quot;]/div[@class=&quot;content-wrapper&quot;]/app-list-api-key[@class=&quot;ng-star-inserted&quot;]/app-msx-paging[1]/div[@class=&quot;row&quot;]/div[@class=&quot;col-6 text-right&quot;]/a[@class=&quot;msx-action btn btn-primary ng-star-inserted&quot;]</value>
      <webElementGuid>765ac1fe-0768-40ee-ba2b-c90eeec46671</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Baru')]</value>
      <webElementGuid>d910553d-2fe3-4fcb-b0b5-3a6280167400</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Daftar API Key'])[1]/following::a[1]</value>
      <webElementGuid>fa73863b-8727-429d-8305-84dca13db4bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Saldo'])[1]/following::a[1]</value>
      <webElementGuid>bd4bbdc0-1cc0-4530-8abd-6aa01338b4b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Filter'])[1]/preceding::a[1]</value>
      <webElementGuid>1ea68833-9eee-4c7b-8244-dd1e48a123ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kode Tenant'])[1]/preceding::a[1]</value>
      <webElementGuid>08aef3f3-7acc-4df8-865b-37a79899bebc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Baru']/parent::*</value>
      <webElementGuid>38dfbbcd-dd76-4885-b40d-59d9f277cbd8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/a</value>
      <webElementGuid>6611913d-30c5-432d-8972-48f84e82890f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[(text() = ' Baru' or . = ' Baru')]</value>
      <webElementGuid>c94e46a1-8a53-4061-b407-f5796a54e79a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
