<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_PRODUCTION</name>
   <tag></tag>
   <elementGuidId>8e786bd7-e3fc-4d6f-be66-b46b6f8e3f92</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#a4ea1a1caf3a-1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='All'])[1]/following::div[6]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>51651a80-a2a2-4077-bf2e-76df33b73ce0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-option ng-star-inserted ng-option-marked</value>
      <webElementGuid>5c5e3bda-caa8-4a1f-9527-329c9411115b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>c63fb63f-adce-4677-bf65-e44cf5eb2c72</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>a4ea1a1caf3a-1</value>
      <webElementGuid>7913dcae-0ca5-4adc-b2c2-9601612bc0f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>PRODUCTION</value>
      <webElementGuid>d4293905-6a60-49e6-9366-d0c54c338a09</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;a4ea1a1caf3a-1&quot;)</value>
      <webElementGuid>0858dec2-636f-4d9a-92d7-9f88de00b3df</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='a4ea1a1caf3a-1']</value>
      <webElementGuid>89874096-920c-4eb7-8a62-56ecda6ac881</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ng-dropdown-panel[@id='a4ea1a1caf3a']/div/div[2]/div[2]</value>
      <webElementGuid>04c3be42-4225-422b-a95a-07b769edc3a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='All'])[2]/following::div[1]</value>
      <webElementGuid>28eb7bd0-6b82-4416-be87-2f35ce69fccb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='All'])[1]/following::div[6]</value>
      <webElementGuid>4c7c98f5-bfd1-4ad6-a799-516c70bc6d63</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='TRIAL'])[1]/preceding::div[1]</value>
      <webElementGuid>59407606-9f2e-46eb-a959-e147a8d3481f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[2]/div[2]</value>
      <webElementGuid>eb572a43-a89c-4da3-a603-8f54bdd294de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'a4ea1a1caf3a-1' and (text() = 'PRODUCTION' or . = 'PRODUCTION')]</value>
      <webElementGuid>51bb2785-94fb-48cb-a3c4-98b0268d49e2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
