<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Active</name>
   <tag></tag>
   <elementGuidId>fb714d30-2aa7-4029-ad5b-7e9588d1ffb4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#accd9d5dfefb-1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='accd9d5dfefb-1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>2ac9eec5-3258-4598-bbb7-5f34908af7a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-option ng-star-inserted ng-option-marked</value>
      <webElementGuid>b8c515bd-1095-491b-9586-c22592563592</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>dcaffeea-def7-4705-a0be-bc11c073e86e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>1a08e985-2b70-441c-a857-0af469514b55</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>accd9d5dfefb-1</value>
      <webElementGuid>5f854942-8283-4c0d-8a36-2319f08325f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Active</value>
      <webElementGuid>edd5134f-6e56-40f2-b81e-7e8733ec9e40</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;accd9d5dfefb-1&quot;)</value>
      <webElementGuid>d82ffafd-556f-4b5c-80b6-1548605e1643</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='accd9d5dfefb-1']</value>
      <webElementGuid>3e0659bf-a847-4b2c-aa0c-9d8cc37a84c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ng-dropdown-panel[@id='accd9d5dfefb']/div/div[2]/div[2]</value>
      <webElementGuid>117245f3-e67a-46fb-893b-7463adc3eeb3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='All'])[2]/following::div[1]</value>
      <webElementGuid>94c4a232-f424-4284-a793-c340ece27f74</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='All'])[1]/following::div[6]</value>
      <webElementGuid>450f3b05-2c00-4117-a82d-4690ca4edf6f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Inactive'])[1]/preceding::div[1]</value>
      <webElementGuid>cd18253a-f477-4eeb-8a28-9c7c82191c48</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[2]/div[2]</value>
      <webElementGuid>9f56f7d3-9b73-4100-9a11-37b354872065</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'accd9d5dfefb-1' and (text() = 'Active' or . = 'Active')]</value>
      <webElementGuid>09ed9384-164a-46d4-9943-91806387e5c1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
