<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_Keluar_ft-x ng-tns-c133-1</name>
   <tag></tag>
   <elementGuidId>d40a5f8c-2a11-4e41-96f0-c70a6293a9dc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>i.ft-x.ng-tns-c133-1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='sidebarClose']/i</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>cfdfddd7-b378-44a4-a551-f30e8d2bf94d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ft-x ng-tns-c133-1</value>
      <webElementGuid>9538d55a-5f49-41dc-8ba7-27277b185bea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;sidebarClose&quot;)/i[@class=&quot;ft-x ng-tns-c133-1&quot;]</value>
      <webElementGuid>21bb8b16-3ede-4852-83c7-b8e751f21d89</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='sidebarClose']/i</value>
      <webElementGuid>8ad87f91-7717-46db-99db-5cbcbd02d022</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[3]/i</value>
      <webElementGuid>966002ce-44bc-45e9-8ce5-c13e1f723cf7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
