<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Active</name>
   <tag></tag>
   <elementGuidId>e8a61103-47af-47a2-9afe-4d600d211f06</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ab0afc3ff1cb-1 > span.ng-option-label.ng-star-inserted</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='All'])[2]/following::span[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>df4d9125-54f4-4964-a67b-036e0341c4c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-option-label ng-star-inserted</value>
      <webElementGuid>51912483-9485-4d05-99a5-2aff8c3f5a5b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-ng-item-label</name>
      <type>Main</type>
      <value>Active</value>
      <webElementGuid>6631a3ce-a2b5-429b-af4c-7759b0c665f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-escape</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>9f7068d3-d017-46d9-8bc7-ba4c47d9538e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Active</value>
      <webElementGuid>a5d0e4ab-1f61-4d0c-8810-4321bb0c6432</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ab0afc3ff1cb-1&quot;)/span[@class=&quot;ng-option-label ng-star-inserted&quot;]</value>
      <webElementGuid>71d00f7f-3d41-4016-982b-f248bbbaaf6d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ab0afc3ff1cb-1']/span</value>
      <webElementGuid>a273b046-dbc2-4f21-a9a5-947fca3c11ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='All'])[2]/following::span[1]</value>
      <webElementGuid>e8d7af14-d780-4b48-92cd-7d6f22f8a71a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='All'])[1]/following::span[6]</value>
      <webElementGuid>8924f669-c7c0-49c1-802f-4d9e5fd4f6ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Inactive'])[1]/preceding::span[1]</value>
      <webElementGuid>bf916078-3e11-40a6-832b-e81c587742dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Set Ulang'])[1]/preceding::span[2]</value>
      <webElementGuid>8759fbf2-2010-4c42-a478-40fa4c668b14</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Active']/parent::*</value>
      <webElementGuid>14a2187a-8886-47d7-ad91-084782f838ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/span</value>
      <webElementGuid>bc08038b-f5af-4605-a28a-367a658aed1c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Active' or . = 'Active')]</value>
      <webElementGuid>19046a49-88ad-4bf4-b88b-fb4d6e574623</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
