<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Tambah</name>
   <tag></tag>
   <elementGuidId>7acc169d-6ba9-483c-aaad-15da494e53d3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@href = 'javascript:' and (text() = 'Tambah' or . = 'Tambah')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.col-6.text-right > a</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='msxForm']/div[4]/div[2]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>7465413e-7cda-4bf1-96f3-ad4c1eab5ee0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:</value>
      <webElementGuid>7489b533-25bb-4d5b-a8ba-efa73ca8e588</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Tambah</value>
      <webElementGuid>d117a568-afcb-4737-86ce-e9f27395f37e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;msxForm&quot;)/div[@class=&quot;row&quot;]/div[@class=&quot;col-6 text-right&quot;]/a[1]</value>
      <webElementGuid>8209cf26-b8e8-4550-b1be-c9aa0841045a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='msxForm']/div[4]/div[2]/a</value>
      <webElementGuid>03fef3c2-2bd3-4553-b156-1f4efc5012a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Tambah')]</value>
      <webElementGuid>484b7ca9-0d2d-48e3-8b84-2a3112f612a5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Layanan'])[1]/following::a[1]</value>
      <webElementGuid>3ea1aa70-a063-4fdc-8bc1-0c105baa69e6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Bank ABC'])[1]/following::a[1]</value>
      <webElementGuid>82e20f9c-098d-4674-a41d-09d3915372ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Belum ada daftar layanan!'])[1]/preceding::a[1]</value>
      <webElementGuid>32f2fd23-dfd3-4655-8591-cd972a5ea326</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Total'])[1]/preceding::a[1]</value>
      <webElementGuid>13de0cdc-91e7-4fa1-9cd6-2225b26e9fd3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Tambah']/parent::*</value>
      <webElementGuid>4d473333-09dd-4571-bc29-bb9a61cf85a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'javascript:')])[4]</value>
      <webElementGuid>fdc57e97-916c-4f75-b93c-5b72370ebfdb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/a</value>
      <webElementGuid>13864425-c3de-430f-9ee7-a6e02b34abaf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'javascript:' and (text() = 'Tambah' or . = 'Tambah')]</value>
      <webElementGuid>9bc8815d-b363-4d25-813f-67311154af7c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
