<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>grandTotal</name>
   <tag></tag>
   <elementGuidId>2144d14e-f2c3-4348-bebb-8ee3d2f9ed6c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#grandTotal</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@type = 'tel' and @id = 'grandTotal' and @placeholder = '0']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='grandTotal']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>49acadf3-4dc7-409b-b047-d0e03238982c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>tel</value>
      <webElementGuid>669f0bb2-73d9-4211-9a37-ebc953b59fd8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>mask</name>
      <type>Main</type>
      <value>separator.0</value>
      <webElementGuid>8bba14eb-2a78-4ceb-bf4f-e92421e9f850</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>thousandseparator</name>
      <type>Main</type>
      <value>.</value>
      <webElementGuid>5c878000-89fd-4f77-9903-07aa0b2f60ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ng-untouched ng-pristine ng-valid</value>
      <webElementGuid>a04837e6-d0b5-4490-a3b7-07d98104d03b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-mask-expression</name>
      <type>Main</type>
      <value>separator.0</value>
      <webElementGuid>71f2caa7-d6d3-40eb-bb4d-293960bfa43e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-thousand-separator</name>
      <type>Main</type>
      <value>.</value>
      <webElementGuid>aaadf3d9-c3a0-4ef9-b1e1-8c485b756898</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-name</name>
      <type>Main</type>
      <value>grandTotal</value>
      <webElementGuid>a47ba6e1-2fc6-4445-acfa-89382f38bb6a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>grandTotal</value>
      <webElementGuid>b50e117e-c06e-45c2-956d-da55fe074581</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>6eb6ccb2-fc5f-458b-a49a-686b775aa0f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;grandTotal&quot;)</value>
      <webElementGuid>09254cea-7472-41c5-808f-0581b85785aa</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='grandTotal']</value>
      <webElementGuid>d51afd00-abd9-4973-86ac-dd0f2bdb3a77</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='msxForm']/div[8]/div/app-currency/fieldset/input</value>
      <webElementGuid>7b8bd7c1-07bf-4d20-a298-80069799c3e6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/div/app-currency/fieldset/input</value>
      <webElementGuid>7f28cfdd-80d7-4ee5-83af-294da1e77a41</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'tel' and @id = 'grandTotal' and @placeholder = '0']</value>
      <webElementGuid>9be3ea34-ab7b-491f-929f-91e4a5db5d24</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
