<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Kupon_kupon</name>
   <tag></tag>
   <elementGuidId>6684f218-c90f-4271-820c-24d938663144</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#kupon</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='kupon']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>49a7e41c-5839-487e-b57f-307c1a92f2a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>f45fc13c-3496-4277-b010-86fbb30976d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ng-untouched ng-pristine ng-valid</value>
      <webElementGuid>0acc8b2d-8428-4cb1-b31f-6ef511b9277d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-name</name>
      <type>Main</type>
      <value>kupon</value>
      <webElementGuid>db9a5c54-c58f-41a8-b13d-40b0c369d880</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>kupon</value>
      <webElementGuid>aef5c8fa-cf21-408f-b86b-003d5bb8cbe7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Type kupon here</value>
      <webElementGuid>47f0df1c-93cd-448c-a0e2-2b5d9f2ce706</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>100</value>
      <webElementGuid>76897b2e-7676-4c0c-bdd7-e379c1cfb275</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;kupon&quot;)</value>
      <webElementGuid>ac07261a-b73d-4d59-b753-99864ec76966</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='kupon']</value>
      <webElementGuid>8b40d8d7-8be8-43de-8a5e-23def0d7e71a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='msxForm']/div[6]/div/app-text/fieldset/div/input</value>
      <webElementGuid>a495dfc6-4d2b-4810-8618-ad3ac5bc4e99</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//fieldset/div/input</value>
      <webElementGuid>c53f6cbd-072f-42bb-aee3-935bd8b97d1a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'kupon' and @placeholder = 'Type kupon here']</value>
      <webElementGuid>a3117d5d-7e06-4437-b1a6-b7c344d5687e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
