<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>notifNoServices</name>
   <tag></tag>
   <elementGuidId>f23d9288-127a-4b3e-8bb2-1b6a3239e359</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>small.text-info</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='msxForm']/div[4]/div[3]/table/tr/td/small</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>small</value>
      <webElementGuid>5051fa03-bed5-49c6-99ae-4c3e185e7e7d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-info</value>
      <webElementGuid>6b20eb4f-10a9-45d8-a245-0816381930c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Belum ada daftar layanan!</value>
      <webElementGuid>2a954701-f8aa-4c2e-ad50-05085ccdd8d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;msxForm&quot;)/div[@class=&quot;row&quot;]/div[@class=&quot;col-12&quot;]/table[@class=&quot;table table-striped table-hover ng-star-inserted&quot;]/tr[1]/td[1]/small[@class=&quot;text-info&quot;]</value>
      <webElementGuid>1d1d9fac-2ca9-4f26-8a06-3dff29426e08</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='msxForm']/div[4]/div[3]/table/tr/td/small</value>
      <webElementGuid>4084d876-f35f-433e-9c9f-38ba28bcf6c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tambah'])[1]/following::small[1]</value>
      <webElementGuid>635b4966-84db-4084-a8b2-d9cbaa615214</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Layanan'])[1]/following::small[1]</value>
      <webElementGuid>8aa0a617-4e1a-4531-898e-4f8c20e848a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Total'])[1]/preceding::small[1]</value>
      <webElementGuid>2fd60dda-6475-4d12-957f-5938b5ecdba5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kupon'])[1]/preceding::small[1]</value>
      <webElementGuid>6f157ec4-f63f-4d6d-b8b2-36edcc9f0ddb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Belum ada daftar layanan!']/parent::*</value>
      <webElementGuid>2de0ffe0-5239-44b1-9eba-c02056fc9129</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//small</value>
      <webElementGuid>8481b964-1f34-4d82-b495-ad98f7005bcc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//small[(text() = ' Belum ada daftar layanan!' or . = ' Belum ada daftar layanan!')]</value>
      <webElementGuid>8928337a-e8d4-4391-87a1-11ceb78bfe5a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
