<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>PPN11</name>
   <tag></tag>
   <elementGuidId>2b4848f6-7171-48db-94e5-442081057596</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ppn</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ppn']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>025c2531-4d38-4dbf-af4c-0ac19534591a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>tel</value>
      <webElementGuid>d15aaf88-c74f-4e86-8502-fe08998f8c2b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>mask</name>
      <type>Main</type>
      <value>separator.0</value>
      <webElementGuid>f0371ebb-b518-47fd-bbf7-c65a4ac3bc15</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>thousandseparator</name>
      <type>Main</type>
      <value>.</value>
      <webElementGuid>04149924-908d-42cb-bdea-5cdbd8e0de76</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ng-untouched ng-pristine ng-valid</value>
      <webElementGuid>864bb016-479a-4078-a4b0-8a9ebcedbc7c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-mask-expression</name>
      <type>Main</type>
      <value>separator.0</value>
      <webElementGuid>8bc4d231-5553-4314-b8fa-4d27b7967015</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-thousand-separator</name>
      <type>Main</type>
      <value>.</value>
      <webElementGuid>23936c66-c87e-451a-9237-058c0f2d279e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-name</name>
      <type>Main</type>
      <value>ppn</value>
      <webElementGuid>7208673d-abfc-46a8-8d0c-8fd8f6b2fa28</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ppn</value>
      <webElementGuid>f2e01ee4-32f8-4486-bb02-da71bde90824</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>f381c39c-3989-43fe-b50d-8c056b082b23</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ppn&quot;)</value>
      <webElementGuid>89c86a1f-1961-4d15-ad05-d9d83fdd670c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ppn']</value>
      <webElementGuid>8dd76046-bdf3-4535-b62b-3b76116cd6c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='msxForm']/div[7]/div/app-currency/fieldset/input</value>
      <webElementGuid>d97a5463-7609-4071-a916-f6c5ff4e798f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/div/app-currency/fieldset/input</value>
      <webElementGuid>5d60b8a9-80b0-4c33-b7a7-75bdef9292a2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'tel' and @id = 'ppn' and @placeholder = '0']</value>
      <webElementGuid>6b91d270-6345-443c-8df0-b2d8a1ba1607</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
