<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_bankdestination</name>
   <tag></tag>
   <elementGuidId>6f9333b4-64c8-455f-ae53-ede33fbd6600</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//ng-select[@id='destinationBank']/div/span[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#destinationBank > div.ng-select-container.ng-has-value > span.ng-arrow-wrapper</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>79d990aa-c8bc-4164-b192-367152fd5110</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-arrow-wrapper</value>
      <webElementGuid>c66b1e29-3962-4119-ada7-0f293357b059</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;destinationBank&quot;)/div[@class=&quot;ng-select-container ng-has-value&quot;]/span[@class=&quot;ng-arrow-wrapper&quot;]</value>
      <webElementGuid>0455ae37-689b-4b0b-b59c-851f49c81225</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ng-select[@id='destinationBank']/div/span[2]</value>
      <webElementGuid>d307d36c-2be0-4caa-97c2-7c6f053f29b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Bank ABC'])[1]/following::span[3]</value>
      <webElementGuid>b53dfb28-2323-4191-997b-77db56fe3898</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select destination bank'])[1]/following::span[5]</value>
      <webElementGuid>e1dae4f2-7f58-4f45-ac74-39f1040eb08a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Layanan'])[1]/preceding::span[2]</value>
      <webElementGuid>5b5ed418-e839-4ba1-96f9-e2f442a075a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tambah'])[1]/preceding::span[2]</value>
      <webElementGuid>9eb76f93-a0a5-4494-8413-0a40a4cf6543</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/app-select/div/ng-select/div/span[2]</value>
      <webElementGuid>e8f62999-1123-4b4b-a1e0-121cf8b91c16</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
