<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_OCR KTP</name>
   <tag></tag>
   <elementGuidId>4ebd7f28-c2df-4328-896b-34e1fba3f103</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='FACECOMPARE'])[1]/following::div[1]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#aca85adc1624-7</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>126fe74f-dae5-445a-ab09-1c6af16ff5c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-option ng-star-inserted ng-option-marked</value>
      <webElementGuid>99652a29-b41c-4a58-b7de-481e8657d47e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>da0702ea-f85d-4005-b62b-b80a9987a61b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>aca85adc1624-7</value>
      <webElementGuid>e48d34c1-a0a2-4f9d-86e3-debf00ce3c3f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>OCR KTP</value>
      <webElementGuid>2c0d3b73-9cc0-4871-8bf3-db007b0f7149</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;aca85adc1624-7&quot;)</value>
      <webElementGuid>9e3e8ff9-a372-44f8-bafa-03e8113ee6a8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='aca85adc1624-7']</value>
      <webElementGuid>4c04f8e9-25c6-461d-a7d4-722cee80731e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ng-dropdown-panel[@id='aca85adc1624']/div/div[2]/div[8]</value>
      <webElementGuid>fe624994-c03f-4382-a575-d87a226ae175</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='FACECOMPARE'])[1]/following::div[1]</value>
      <webElementGuid>f163d515-8db6-41b3-b0ea-fa6337b95159</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='OCR STNK'])[1]/following::div[2]</value>
      <webElementGuid>4d6049ab-fad2-4d70-9edc-b9b06ab1136f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='OCR NPWP'])[1]/preceding::div[1]</value>
      <webElementGuid>7bc1be66-5e7e-4654-be6c-cccd8424deaa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]</value>
      <webElementGuid>09d64be5-9d1a-44e2-b1f8-73c8524a20a0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'aca85adc1624-7' and (text() = 'OCR KTP' or . = 'OCR KTP')]</value>
      <webElementGuid>3b9e910c-72ea-40b9-9c35-cb2da15c4318</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
