<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Kode Kupon</name>
   <tag></tag>
   <elementGuidId>45b85baf-5bf1-4e2b-99a3-3b86bced2110</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#couponCode</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='couponCode']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>fcdfad34-2155-42a3-a00c-7ee052a64e3e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>4cf97e28-ad72-4c40-bec8-e26634090459</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ng-untouched ng-pristine ng-valid</value>
      <webElementGuid>ca923065-c65c-43fa-8f06-827fed627ffc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-name</name>
      <type>Main</type>
      <value>couponCode</value>
      <webElementGuid>94bfad4f-7b4d-40b7-9b3c-af03db3a2396</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>couponCode</value>
      <webElementGuid>e8c4a2cb-034e-4681-9052-cc084165d365</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Ketik kode kupon di sini</value>
      <webElementGuid>c7db85d1-107c-47d2-89a4-75ebb2d0d26a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;couponCode&quot;)</value>
      <webElementGuid>49513b47-679f-4052-be12-ce68c187be9b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='couponCode']</value>
      <webElementGuid>6009b9a5-fcb4-4f5b-89ef-84f92211f58a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='searchForm']/div/div[2]/app-question/app-text/div/div[2]/div/input</value>
      <webElementGuid>b361caca-daf2-4b3b-b59f-ac2b96f80037</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/input</value>
      <webElementGuid>b112c206-544a-4fe3-a0ed-d62a48bb47ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'couponCode' and @placeholder = 'Ketik kode kupon di sini']</value>
      <webElementGuid>836ee0ed-63f1-4b37-9733-918d7c757d36</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
