<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>setUlang</name>
   <tag></tag>
   <elementGuidId>f387baff-090a-4ad1-b9c8-bc20e98304e9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>i.ft-delete</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='searchForm']/div[2]/div/button/i</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>3093ca86-9380-4173-97e9-dd5b072108e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ft-delete</value>
      <webElementGuid>d531d04d-4939-4611-b95e-a845a5de9163</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;searchForm&quot;)/div[@class=&quot;row&quot;]/div[@class=&quot;col-12 text-right&quot;]/button[@class=&quot;btn btn-secondary mr-2&quot;]/i[@class=&quot;ft-delete&quot;]</value>
      <webElementGuid>c39789df-d0b9-4432-bcc7-2f29d32f09d7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='searchForm']/div[2]/div/button/i</value>
      <webElementGuid>d3d6c341-0ae6-4173-80dd-8e7717baf6c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button/i</value>
      <webElementGuid>7ec20be7-5c56-4aeb-9530-f15b00fcd727</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
