<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Tanggal Terakhir Berlaku Akhir</name>
   <tag></tag>
   <elementGuidId>ec9f92d6-66d0-4dda-87a4-ea54bc2d57b4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#couponEndDateEnd</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='couponEndDateEnd']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>7e96df5e-2980-4171-8249-b4aabb3cb4bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>99b597ac-1cb6-4974-b37c-d18d5215d6ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ng-untouched ng-pristine ng-invalid</value>
      <webElementGuid>d989bbb3-1a42-4fc1-ab5a-a14dd4ec3d93</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-name</name>
      <type>Main</type>
      <value>couponEndDateEnd</value>
      <webElementGuid>25fe491f-85b9-41dd-93fe-4f337515ccde</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>couponEndDateEnd</value>
      <webElementGuid>f9603791-865e-4c8a-96f4-f76aeebe359d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>yyyy-mm-dd</value>
      <webElementGuid>ebeda5c5-bfe3-4d14-be48-92ee3cf93e67</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;couponEndDateEnd&quot;)</value>
      <webElementGuid>40f3222d-6088-4de9-a7b3-2923416202f8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='couponEndDateEnd']</value>
      <webElementGuid>5242adfa-8774-4df2-a754-a0552d8ea3d6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='searchForm']/div/div[8]/app-question/app-date/div/div[2]/div/input</value>
      <webElementGuid>ae281573-9d06-48b8-9a24-aaa19e025fff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/app-question/app-date/div/div[2]/div/input</value>
      <webElementGuid>ec0406c8-3a14-474b-83ab-e93a804b8438</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'couponEndDateEnd' and @placeholder = 'yyyy-mm-dd']</value>
      <webElementGuid>b6c42070-e0d7-450b-9bbf-f5ca1ba6ed9f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
