<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>tanggal Mulai Berlaku Akhir</name>
   <tag></tag>
   <elementGuidId>305d3dae-886e-4be7-a1e3-9ce8f802d1e3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#couponStartDateEnd</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='couponStartDateEnd']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>17de5af8-7a95-43a8-96b9-ba7502adec24</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>97ccbc7c-7a58-4e7e-beeb-8f10820b87c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ng-untouched ng-pristine ng-invalid</value>
      <webElementGuid>9cf547ac-cf05-4f70-a8a4-d990b94487e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-name</name>
      <type>Main</type>
      <value>couponStartDateEnd</value>
      <webElementGuid>85e05bc9-03eb-4e56-ad82-bc800435e912</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>couponStartDateEnd</value>
      <webElementGuid>79209169-1891-457c-b300-571d3530bf1d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>yyyy-mm-dd</value>
      <webElementGuid>716ccb57-f8d1-4001-9daa-669bb327b5e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;couponStartDateEnd&quot;)</value>
      <webElementGuid>639398f4-94a5-49ea-b1e9-0d2e08b5ed2b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='couponStartDateEnd']</value>
      <webElementGuid>ba9f7145-eade-4c11-9b96-e46b1d8f60a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='searchForm']/div/div[6]/app-question/app-date/div/div[2]/div/input</value>
      <webElementGuid>e836c877-6e98-41ae-b21f-7621f68358f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/app-question/app-date/div/div[2]/div/input</value>
      <webElementGuid>181630be-2ca3-4a11-bd57-062cfa22e181</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'couponStartDateEnd' and @placeholder = 'yyyy-mm-dd']</value>
      <webElementGuid>68331c13-72ad-42d2-9fb1-c68484d57df5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
