<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Tanggal Mulai Berlaku Awal</name>
   <tag></tag>
   <elementGuidId>2473186a-a1a0-455e-8e8d-f3536a568c4e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#couponStartDateStart</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='couponStartDateStart']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>49bb3923-940a-4408-9e43-90d7e0b22c6d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>67531eea-26d0-4e13-975d-fdfe208a9390</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ng-untouched ng-pristine ng-invalid</value>
      <webElementGuid>fe4b1385-2e9e-4f4c-b6ca-d8d604566e09</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-name</name>
      <type>Main</type>
      <value>couponStartDateStart</value>
      <webElementGuid>c2debd57-e99a-4fe5-bd1a-7e2c92901dd8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>couponStartDateStart</value>
      <webElementGuid>2ca881f1-d0a5-4e1b-914e-3452ae9558a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>yyyy-mm-dd</value>
      <webElementGuid>d38da379-61dc-4977-bc9e-9a090300dff6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;couponStartDateStart&quot;)</value>
      <webElementGuid>f0e1b43d-5aa7-4561-a609-d603cb7aa82a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='couponStartDateStart']</value>
      <webElementGuid>3bebfca4-561c-47f0-a4c6-4c14bb894bbb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='searchForm']/div/div[5]/app-question/app-date/div/div[2]/div/input</value>
      <webElementGuid>e72c7505-a854-41ae-b9e9-f3b8f8b1deb4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//app-date/div/div[2]/div/input</value>
      <webElementGuid>04da95a0-51bc-44b5-88a5-7c66904564bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'couponStartDateStart' and @placeholder = 'yyyy-mm-dd']</value>
      <webElementGuid>4d6f9ca3-0705-4c03-8c4e-3ba80ba03e85</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
