<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Tanggal Terakhir Berlaku Awal</name>
   <tag></tag>
   <elementGuidId>228924f6-017d-400e-af54-d7d45b9ff47e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#couponEndDateStart</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='couponEndDateStart']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>88a57290-5371-41a7-82af-d1b828bfddf2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>9559a5f6-72de-4940-8837-4e9b3633b79b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ng-untouched ng-pristine ng-invalid</value>
      <webElementGuid>977abcf7-bbb0-420d-b7f2-b130d1b48a84</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-name</name>
      <type>Main</type>
      <value>couponEndDateStart</value>
      <webElementGuid>c61a1068-9b8c-45bd-8cd2-36d6d1717db1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>couponEndDateStart</value>
      <webElementGuid>6fbdef3c-e1db-44d8-b2eb-2f3da9f23308</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>yyyy-mm-dd</value>
      <webElementGuid>4e2df8fd-38d4-4f93-93ff-6c77016057db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;couponEndDateStart&quot;)</value>
      <webElementGuid>b23d0e33-8b26-48e9-a9e8-4e667dd2af5f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='couponEndDateStart']</value>
      <webElementGuid>859eff51-e4e7-43c2-8c06-eb34e802ce84</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='searchForm']/div/div[7]/app-question/app-date/div/div[2]/div/input</value>
      <webElementGuid>c8b0733c-9835-46cd-bc06-52faf59d28d6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/app-question/app-date/div/div[2]/div/input</value>
      <webElementGuid>3ea873f6-12eb-4014-a894-221bb3ed7647</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'couponEndDateStart' and @placeholder = 'yyyy-mm-dd']</value>
      <webElementGuid>594be143-3aee-4db8-a419-5d12fa694f21</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
