<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Batal</name>
   <tag></tag>
   <elementGuidId>c4a83659-cd7e-4210-9be0-46cf0c833df5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;msxForm&quot;]/div[2]/div/button[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;msxForm&quot;]/div[2]/div/button[1]</value>
      <webElementGuid>b48175f1-9286-401a-8cf3-7869a4ade146</webElementGuid>
   </webElementProperties>
</WebElementEntity>
