<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Code 1202  Tidak bisa memiliki lebih dari 1 tipe api key yang sama</name>
   <tag></tag>
   <elementGuidId>403fb9b5-6663-40b8-a6b0-1867cd78652e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='toast-container']/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.ng-tns-c95-2.ng-star-inserted.ng-trigger.ng-trigger-flyInOut.ngx-toastr.toast-error</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>481a6d23-b593-4906-8994-a70f5ee02d16</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-tns-c95-2 ng-star-inserted ng-trigger ng-trigger-flyInOut ngx-toastr toast-error</value>
      <webElementGuid>831a7189-8d29-492d-b350-525de5064d16</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Code: 1202  Tidak bisa memiliki lebih dari 1 tipe api key yang sama. </value>
      <webElementGuid>cb0e7525-22ea-4d2e-bf0b-bec6d81dced6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;toast-container&quot;)/div[@class=&quot;ng-tns-c95-2 ng-star-inserted ng-trigger ng-trigger-flyInOut ngx-toastr toast-error&quot;]</value>
      <webElementGuid>ad030c8a-3609-4343-8f87-eea58352bde4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='toast-container']/div</value>
      <webElementGuid>900bd463-edbd-4cec-94d2-e9e5dfe88f15</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='`'])[2]/following::div[4]</value>
      <webElementGuid>3027b894-1c86-4d17-b82b-cec10a0f7202</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Alt'])[2]/following::div[4]</value>
      <webElementGuid>e64d8b0b-bee3-46e2-80f0-7c8cda76f632</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div</value>
      <webElementGuid>e3eb2d3f-335f-4263-8f52-5af35a81a6ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = ' Code: 1202  Tidak bisa memiliki lebih dari 1 tipe api key yang sama. ' or . = ' Code: 1202  Tidak bisa memiliki lebih dari 1 tipe api key yang sama. ')]</value>
      <webElementGuid>4544965d-ad9d-426f-bb98-8233e5a2a57c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
