<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__apiKeyName</name>
   <tag></tag>
   <elementGuidId>9c8b17d0-302f-4f20-b7f4-b991e087ac79</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#apiKeyName</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='apiKeyName']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>61ce912c-1d6c-4a4b-a512-03809fdf8596</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>1efde59c-3267-4922-8f4c-09c456591e0a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>apiKeyName</value>
      <webElementGuid>e2a7c395-92b3-4b13-837b-1f476ac7c322</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>apiKeyName</value>
      <webElementGuid>f182ea04-ec7a-4afd-b055-e55c83b15571</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Nama API Key</value>
      <webElementGuid>82082b9d-01f3-4247-a504-ac7410b45a90</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control mb-2 ng-untouched ng-pristine ng-invalid</value>
      <webElementGuid>4be04ba4-ab1b-4e3d-b7dc-8da67d0e4610</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-name</name>
      <type>Main</type>
      <value>apiKeyName</value>
      <webElementGuid>9057c4f2-980e-4ec0-a5ba-8ae2a9f8bfe8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-required</name>
      <type>Main</type>
      <value>required</value>
      <webElementGuid>ffd9c350-6fe6-4ab1-ad0e-e948ac48af64</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-ng-style</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>ef8ea5e9-5dbc-48d2-8f3f-8e7536278309</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;apiKeyName&quot;)</value>
      <webElementGuid>d31c339d-d352-4292-8632-3fa35c0f689c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='apiKeyName']</value>
      <webElementGuid>6bd3cfb9-f7cb-464e-ae25-368a9f0063ec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>c5249c3b-e936-4496-a096-a0d39f21686b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'apiKeyName' and @placeholder = 'Nama API Key']</value>
      <webElementGuid>51a606b9-1854-4fb2-a705-abaa3b407362</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
