<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Tipe API KeyPRODUCTIONTRIAL</name>
   <tag></tag>
   <elementGuidId>787eb7fe-ce04-47d7-bc05-add53d0bd3b8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#apiKeyType</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='apiKeyType']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>16c2838c-f63b-44c5-afac-d271ac9c7488</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>apiKeyType</value>
      <webElementGuid>63cc2a12-e636-415c-b9ef-6cdf9af62bce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>apiKeyType</value>
      <webElementGuid>b236a9e2-86a8-4e5c-a25e-dc52f86e45ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Tipe API Key</value>
      <webElementGuid>30a251a0-777b-4162-a8c5-80ee544cfa99</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control mb-2 ng-untouched ng-pristine ng-valid</value>
      <webElementGuid>99a2a380-7fab-4ee4-a0dd-b0a18e0b3522</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-name</name>
      <type>Main</type>
      <value>apiKeyType</value>
      <webElementGuid>003ccdf7-b080-4595-8d23-de0af070f87c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-required</name>
      <type>Main</type>
      <value>required</value>
      <webElementGuid>c45eabeb-7e37-413d-9840-29d22031aae9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-ng-style</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>7f5bbc4e-28e8-443e-b100-a988f2eb0924</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Tipe API KeyPRODUCTIONTRIAL</value>
      <webElementGuid>9c823176-e885-4c75-aad6-f465d7063bbd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;apiKeyType&quot;)</value>
      <webElementGuid>d0acfcea-681a-4c74-9d97-f36f7dfd6f46</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='apiKeyType']</value>
      <webElementGuid>3e809822-d082-4ee4-9d84-1bae89f2b7e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[2]/following::select[1]</value>
      <webElementGuid>35f9687c-52aa-49f3-821a-aa07d11977bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Batal'])[1]/preceding::select[1]</value>
      <webElementGuid>ffee1ff0-8b04-4687-8af5-d6b6962d8d4a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Simpan'])[1]/preceding::select[1]</value>
      <webElementGuid>0756edc1-fa3f-4940-ad98-01d479a38296</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>c2d654e2-0f88-4f01-83ec-c3f87d5fe620</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'apiKeyType' and @placeholder = 'Tipe API Key' and (text() = 'Tipe API KeyPRODUCTIONTRIAL' or . = 'Tipe API KeyPRODUCTIONTRIAL')]</value>
      <webElementGuid>47085c3f-f37f-4743-86e7-9a6c5306f105</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
