<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_tipeAPI</name>
   <tag></tag>
   <elementGuidId>787eb7fe-ce04-47d7-bc05-add53d0bd3b8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;apiKeyType&quot;]/div/div/div[3]/input</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='apiKeyType']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#apiKeyType</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>484d876c-4110-4043-8318-478330a42a3f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>apiKeyType</value>
      <webElementGuid>efee536a-5887-48f4-a090-b9123ddc3d1e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>apiKeyType</value>
      <webElementGuid>85b43639-af7f-4476-828d-4be5c9ca6497</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Tipe API Key</value>
      <webElementGuid>5901c455-98ea-4b98-b49d-c863ae15e767</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control mb-2 ng-untouched ng-pristine ng-valid</value>
      <webElementGuid>0f56d662-448b-49df-be01-caa12a91ac53</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-name</name>
      <type>Main</type>
      <value>apiKeyType</value>
      <webElementGuid>d40cb482-ad43-47a8-b083-ee424ad8c5a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-required</name>
      <type>Main</type>
      <value>required</value>
      <webElementGuid>c2e63513-6b8d-46b2-a468-dbc36d3346de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-ng-style</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>ee8a3ba6-e02b-430f-bca8-ea8968b8aa6a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Tipe API KeyPRODUCTIONTRIAL</value>
      <webElementGuid>306a8e1a-3bcc-4672-bc36-b80af7149739</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;apiKeyType&quot;]/div/div/div[3]/input</value>
      <webElementGuid>d4eb3622-b683-4344-8283-f0331b67eba2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='apiKeyType']</value>
      <webElementGuid>817f6fbf-5b7d-4c81-b168-cedb497787f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[2]/following::select[1]</value>
      <webElementGuid>531883b6-c656-4b89-a65b-76399a48cf24</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Batal'])[1]/preceding::select[1]</value>
      <webElementGuid>8bed7a29-ecf6-4f8e-972f-8e464bb038bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Simpan'])[1]/preceding::select[1]</value>
      <webElementGuid>845b1e3b-2c98-4474-8189-2486868916f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>0d8d3821-5fe1-421a-b811-36ef1c1b5df8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'apiKeyType' and @placeholder = 'Tipe API Key' and (text() = 'Tipe API KeyPRODUCTIONTRIAL' or . = 'Tipe API KeyPRODUCTIONTRIAL')]</value>
      <webElementGuid>1cdb796e-e702-42c7-9d90-ccb3c7cca9d9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
