<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_Lanjutkan Perjalanan Anda_c-sjeemv2ss1l</name>
   <tag></tag>
   <elementGuidId>93573782-e448-474b-a9e0-77e5477a3bf8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>iframe[name=&quot;c-sjeemv2ss1l&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@name='c-sjeemv2ss1l']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>fa492f73-8520-4d6c-92b4-9e366a3ca583</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>masa berlaku tantangan recaptcha akan berakhir dalam dua menit</value>
      <webElementGuid>6e85aa8c-beff-4050-b1da-1ee20c06d4d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://www.google.com/recaptcha/api2/bframe?hl=id&amp;v=MuIyr8Ej74CrXhJDQy37RPBe&amp;k=6LcDnrckAAAAAOvOHY_-Rd-L-T6KyqwMtloQn_61</value>
      <webElementGuid>75ef7a94-b1d5-4737-b8e7-1d5e1d275cdd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>c-sjeemv2ss1l</value>
      <webElementGuid>9c9a058b-e148-480d-9106-c36889b0696e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>e2b6f8ea-0384-418e-b9cb-76d3c5cb7d0f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scrolling</name>
      <type>Main</type>
      <value>no</value>
      <webElementGuid>11fa0a77-3c6e-43a1-b16d-78f7306f051c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>sandbox</name>
      <type>Main</type>
      <value>allow-forms allow-popups allow-same-origin allow-scripts allow-top-navigation allow-modals allow-popups-to-escape-sandbox</value>
      <webElementGuid>3b1a8a7f-f8f8-458a-ae4a-f415fce037c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;auth-page blank-page pace-done pace-done&quot;]/div[4]/div[4]/iframe[1]</value>
      <webElementGuid>baa6fbd6-985a-47a2-9aeb-402f8b3c6d28</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@name='c-sjeemv2ss1l']</value>
      <webElementGuid>cf104330-e37d-4e96-96da-66e536ba7bf1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/iframe</value>
      <webElementGuid>7cf621f0-7fa3-4001-a75d-37a30aeed116</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@title = 'masa berlaku tantangan recaptcha akan berakhir dalam dua menit' and @src = 'https://www.google.com/recaptcha/api2/bframe?hl=id&amp;v=MuIyr8Ej74CrXhJDQy37RPBe&amp;k=6LcDnrckAAAAAOvOHY_-Rd-L-T6KyqwMtloQn_61' and @name = 'c-sjeemv2ss1l']</value>
      <webElementGuid>ca9ccbba-d1dd-4471-be4e-4b79101414d3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
