<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_Lupa Kata Sandi_a-ahh08nxacpoi</name>
   <tag></tag>
   <elementGuidId>345a15d7-cd6d-4192-8e84-3b3b4df66f25</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@name='a-ahh08nxacpoi']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>iframe[name=&quot;a-ahh08nxacpoi&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>52b746aa-eec7-41a0-9f17-b04113a20848</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>reCAPTCHA</value>
      <webElementGuid>3b67f933-10df-4082-83c3-4ae61ad0a86a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://www.google.com/recaptcha/api2/anchor?ar=1&amp;k=6LcDnrckAAAAAOvOHY_-Rd-L-T6KyqwMtloQn_61&amp;co=aHR0cDovL2dka3dlYnN2cjo0MTAw&amp;hl=id&amp;type=image&amp;v=MuIyr8Ej74CrXhJDQy37RPBe&amp;theme=light&amp;size=normal&amp;cb=az56egp2ge71</value>
      <webElementGuid>18d8c41c-992d-4071-9cea-917304dc41d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>304</value>
      <webElementGuid>c0947ca5-00bb-4a7e-8829-ad02c7f6605a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>78</value>
      <webElementGuid>b8f91421-8b22-4eb1-a5b3-5a442fc7d8c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>presentation</value>
      <webElementGuid>656db458-6223-41c8-b734-d2376564ff7b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>a-ahh08nxacpoi</value>
      <webElementGuid>b38b893a-81c5-419a-901b-8caff20894e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>d77246e8-c25b-498a-b463-0326318aff59</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scrolling</name>
      <type>Main</type>
      <value>no</value>
      <webElementGuid>7ad4f6db-5ead-4f1e-b771-84b97e97e75e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>sandbox</name>
      <type>Main</type>
      <value>allow-forms allow-popups allow-same-origin allow-scripts allow-top-navigation allow-modals allow-popups-to-escape-sandbox</value>
      <webElementGuid>b0ace91b-0071-4bec-935a-9551101e32e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ngx_captcha_id_9539&quot;)/div[1]/div[1]/iframe[1]</value>
      <webElementGuid>85f766fe-3b8f-495c-856f-16d185cc04ed</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@name='a-ahh08nxacpoi']</value>
      <webElementGuid>79678307-3db1-48a5-adb0-091644d73037</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ngx_captcha_id_9539']/div/div/iframe</value>
      <webElementGuid>1a23888b-b468-4724-9782-6f70593860ac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div/iframe</value>
      <webElementGuid>bf70cdc7-0f5d-4b05-8068-7451badde490</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@title = 'reCAPTCHA' and @src = 'https://www.google.com/recaptcha/api2/anchor?ar=1&amp;k=6LcDnrckAAAAAOvOHY_-Rd-L-T6KyqwMtloQn_61&amp;co=aHR0cDovL2dka3dlYnN2cjo0MTAw&amp;hl=id&amp;type=image&amp;v=MuIyr8Ej74CrXhJDQy37RPBe&amp;theme=light&amp;size=normal&amp;cb=az56egp2ge71' and @name = 'a-ahh08nxacpoi']</value>
      <webElementGuid>6268e252-d5ca-4545-8c36-ef5088d56334</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
