<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_motor_rc-image-tile-33</name>
   <tag></tag>
   <elementGuidId>54986e44-45a4-4008-b9e8-95a665a954a5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='rc-imageselect-target']/table/tbody/tr[3]/td[2]/div/div/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>1199e3d5-6634-40db-9048-e46995d02511</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>rc-image-tile-33</value>
      <webElementGuid>6063e586-9cc7-4003-b7d6-21edccdbfa17</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://www.google.com/recaptcha/api2/payload?p=06AFY_a8Ve4iTrOXB98kfw0sganMC1FYCtAV-9WT2ulnzu33HTX4SxXzqDuFJGNTBaHJhH9R8d364EjgjnyB8Wywx8Dc1zVYtX1c9HW2ZxH6Y0WmMse85ITg0D4A5cHVBMeobwBFdhrp0OZyB7SDgTs0RjXzxIRFSdmonngy6IajBIXLjreE6hs8RY20FhNyHXps9C473DHH5br7o_74wc-HhlyolZ8HdqSg&amp;k=6LcDnrckAAAAAOvOHY_-Rd-L-T6KyqwMtloQn_61</value>
      <webElementGuid>d285038b-b86b-475b-922d-2d0a2a84666b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;rc-imageselect-target&quot;)/table[@class=&quot;rc-imageselect-table-33&quot;]/tbody[1]/tr[3]/td[@class=&quot;rc-imageselect-tile&quot;]/div[@class=&quot;rc-image-tile-target&quot;]/div[@class=&quot;rc-image-tile-wrapper&quot;]/img[@class=&quot;rc-image-tile-33&quot;]</value>
      <webElementGuid>2741c396-8dcb-4c63-9e1c-1799cf3f6941</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/API_KEY/Page_Login - eendigo Platform/iframe_Lanjutkan Perjalanan Anda_c-sjeemv2ss1l</value>
      <webElementGuid>ba758fde-8315-4f77-a0c0-b690ad18790f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='rc-imageselect-target']/table/tbody/tr[3]/td[2]/div/div/img</value>
      <webElementGuid>77e42a3d-e623-4935-bbd7-6073a770f1de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[contains(@src,'https://www.google.com/recaptcha/api2/payload?p=06AFY_a8Ve4iTrOXB98kfw0sganMC1FYCtAV-9WT2ulnzu33HTX4SxXzqDuFJGNTBaHJhH9R8d364EjgjnyB8Wywx8Dc1zVYtX1c9HW2ZxH6Y0WmMse85ITg0D4A5cHVBMeobwBFdhrp0OZyB7SDgTs0RjXzxIRFSdmonngy6IajBIXLjreE6hs8RY20FhNyHXps9C473DHH5br7o_74wc-HhlyolZ8HdqSg&amp;k=6LcDnrckAAAAAOvOHY_-Rd-L-T6KyqwMtloQn_61')])[8]</value>
      <webElementGuid>fe5ca414-8016-4d40-b59b-ea72590ccdb8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[3]/td[2]/div/div/img</value>
      <webElementGuid>e9f2aa5f-2bca-42eb-a116-501e8f7cb5a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://www.google.com/recaptcha/api2/payload?p=06AFY_a8Ve4iTrOXB98kfw0sganMC1FYCtAV-9WT2ulnzu33HTX4SxXzqDuFJGNTBaHJhH9R8d364EjgjnyB8Wywx8Dc1zVYtX1c9HW2ZxH6Y0WmMse85ITg0D4A5cHVBMeobwBFdhrp0OZyB7SDgTs0RjXzxIRFSdmonngy6IajBIXLjreE6hs8RY20FhNyHXps9C473DHH5br7o_74wc-HhlyolZ8HdqSg&amp;k=6LcDnrckAAAAAOvOHY_-Rd-L-T6KyqwMtloQn_61']</value>
      <webElementGuid>36bf3acd-bd90-4b18-b8c6-90b41eeb6feb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
