<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_ADINS</name>
   <tag></tag>
   <elementGuidId>0092c93b-effd-47bb-a852-766a80225ccc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ab9a3b6bfec7-1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='ab9a3b6bfec7-1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>34836b5b-9763-4a0f-9668-8644c4c572c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-option ng-option-selected ng-star-inserted ng-option-marked</value>
      <webElementGuid>0367449e-054b-4bf8-a7d8-709da9cd1c50</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>6d4c86e0-bd9d-4917-93a0-3a126aad3d51</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>417eba99-789d-46bd-9e45-1364d4677c99</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ab9a3b6bfec7-1</value>
      <webElementGuid>5040da09-765f-46b3-83c3-30445e56cf31</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>ADINS</value>
      <webElementGuid>cfba7e54-7acf-4f03-9cc0-3e5aa08eb077</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ab9a3b6bfec7-1&quot;)</value>
      <webElementGuid>720c1b41-4dff-4319-81a1-61010cd1219d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='ab9a3b6bfec7-1']</value>
      <webElementGuid>3b12ca76-5405-4828-af23-40aa8f9c72a2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ng-dropdown-panel[@id='ab9a3b6bfec7']/div/div[2]/div[2]</value>
      <webElementGuid>d77241e5-8fec-44d1-88f6-29c2d7f7806f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pilih Vendor'])[1]/following::div[1]</value>
      <webElementGuid>600272bf-577f-4ec8-a8b0-cb1c0488517f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ADINS'])[1]/following::div[6]</value>
      <webElementGuid>0c2e7b57-044e-4f71-a246-e62e98726238</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tipe Saldo'])[1]/preceding::div[1]</value>
      <webElementGuid>bf3762d5-aa0a-4a02-a506-8a401ef0480d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[2]/div[2]</value>
      <webElementGuid>719d4062-ff03-4f5b-aac7-44ca31e68598</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'ab9a3b6bfec7-1' and (text() = 'ADINS' or . = 'ADINS')]</value>
      <webElementGuid>63bc397d-3852-4b4b-987c-1a6f75c5e9b2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
