<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Inactive</name>
   <tag></tag>
   <elementGuidId>7cc5863b-8592-41d2-a329-6309df130ba2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#a01fcba93224-2</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='a01fcba93224-2']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>f5c7c800-6a9e-4f7f-bee2-e9fae8a3352f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-option ng-star-inserted ng-option-marked</value>
      <webElementGuid>2270be27-0b20-432e-a2ac-fc231a696422</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>0eb34d84-08f5-40b2-b03f-1dd47216ca88</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>e7f80289-c85d-4d04-aca7-7259017c6c80</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>a01fcba93224-2</value>
      <webElementGuid>76b87116-3184-4bf1-b5af-2d7ae38bcc7e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Inactive</value>
      <webElementGuid>bb94bdf9-9f4b-4c22-8ce8-81349129b50d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;a01fcba93224-2&quot;)</value>
      <webElementGuid>342ea7aa-3496-4497-9e43-9a2d3818793f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='a01fcba93224-2']</value>
      <webElementGuid>da1355af-169b-47bf-9166-7fcfcbb9d4ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ng-dropdown-panel[@id='a01fcba93224']/div/div[2]/div[3]</value>
      <webElementGuid>1d8e52b8-03bc-435c-aa82-31bd9d1155bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Active'])[2]/following::div[1]</value>
      <webElementGuid>43818c04-e8f8-4132-bb9e-34a651982ba1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='All'])[1]/following::div[2]</value>
      <webElementGuid>25d32764-9da5-44d2-87a0-3bde5329c728</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Set Ulang'])[1]/preceding::div[1]</value>
      <webElementGuid>5d939158-a1ed-4653-8cb4-20831595c7f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[2]/div[3]</value>
      <webElementGuid>8596dd52-4302-4d6f-bb07-42b70a5da740</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'a01fcba93224-2' and (text() = 'Inactive' or . = 'Inactive')]</value>
      <webElementGuid>7d798159-3668-447c-96aa-fc13a55986db</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
