<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_SMS Finance</name>
   <tag></tag>
   <elementGuidId>11c6d9a9-3c6c-4329-958c-5966309eee99</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#a09c16341fea-1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='a09c16341fea-1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>ddc9561c-9d8e-4801-80bc-c22a1d8509cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-option ng-star-inserted ng-option-marked</value>
      <webElementGuid>054fd079-e16d-46e5-8083-ee7a9cd55b58</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>201bc8f6-5185-4b42-97bf-6db9bbba6970</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>a09c16341fea-1</value>
      <webElementGuid>0d1a98b6-9d27-46fc-924e-6db360bc7d5b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>SMS Finance</value>
      <webElementGuid>e9e02147-c3b7-4524-92ce-90243a19c370</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;a09c16341fea-1&quot;)</value>
      <webElementGuid>162ddb05-8d72-469a-b127-8223aabf76bb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='a09c16341fea-1']</value>
      <webElementGuid>06083432-a67d-480a-86d0-b90575009cb1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ng-dropdown-panel[@id='a09c16341fea']/div/div[2]/div[2]</value>
      <webElementGuid>88acaf5c-cdc9-48bd-88dc-bb601cc0b0e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pilih Tenant'])[2]/following::div[1]</value>
      <webElementGuid>f64bbe79-51d9-4fd1-86eb-1c984f5079bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pilih Tenant'])[1]/following::div[6]</value>
      <webElementGuid>d633888c-085c-4617-ab8a-7604840f9ddf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='BRI Finance'])[1]/preceding::div[1]</value>
      <webElementGuid>2aaec826-6c17-40ff-9352-51b7852d41ac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[2]/div[2]</value>
      <webElementGuid>a0671aad-d9e6-4622-8a61-78b67bd4bb31</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'a09c16341fea-1' and (text() = 'SMS Finance' or . = 'SMS Finance')]</value>
      <webElementGuid>dedcb916-17f2-499c-a390-a6166c9e0beb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
