<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_Tanggal Pembelian_fa fa-calendar</name>
   <tag></tag>
   <elementGuidId>5f90a461-90c8-4d1b-b232-385147b9d0f1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>i.fa.fa-calendar</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='xForm']/div/div[7]/app-date/fieldset/div/div/div/i</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>3198ccc3-dcbb-4ffd-8bab-3c3adcb74478</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fa fa-calendar</value>
      <webElementGuid>7e0c5f96-c684-4b54-bf63-526b6c814c03</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;xForm&quot;)/div[@class=&quot;row&quot;]/div[@class=&quot;col-12&quot;]/app-date[1]/fieldset[@class=&quot;form-group ng-invalid ng-star-inserted ng-touched ng-dirty&quot;]/div[@class=&quot;input-group&quot;]/div[@class=&quot;input-group-append&quot;]/div[@class=&quot;input-group-text&quot;]/i[@class=&quot;fa fa-calendar&quot;]</value>
      <webElementGuid>8aef1452-57eb-4408-b0b8-4fad117c387f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='xForm']/div/div[7]/app-date/fieldset/div/div/div/i</value>
      <webElementGuid>7ebacf41-08e3-47b7-94ce-e7123b0d75a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//fieldset/div/div/div/i</value>
      <webElementGuid>2c0c4fb9-b77c-42ae-866b-dfd7c26c5c26</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
