<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Verifikasi Dukcapil Tanpa Biometrik_D_0d87e0</name>
   <tag></tag>
   <elementGuidId>b2b92183-973b-4714-9d1f-ab94157b73be</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='DUKCAPIL_NOBIO@INDR']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e9174b64-ffbc-4368-af42-581bcf9f5ea6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>b0efc0b3-b01f-4cc7-a44a-566fcdeb5000</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-check-input ng-star-inserted</value>
      <webElementGuid>816a8a9b-da40-4086-b2c5-1ff02195ed9b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>DUKCAPIL_NOBIO@INDR</value>
      <webElementGuid>84b2134f-fcd9-40b7-8367-a49873e0b486</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;DUKCAPIL_NOBIO@INDR&quot;)</value>
      <webElementGuid>f88b386b-ffbc-4684-ab30-6b5d6b2e1622</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='DUKCAPIL_NOBIO@INDR']</value>
      <webElementGuid>32f6b3ee-dd6b-4dcc-82af-4bb75a48364e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[115]/input</value>
      <webElementGuid>3debb3d3-fd1b-46ff-a694-0a883a988b4d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @id = 'DUKCAPIL_NOBIO@INDR']</value>
      <webElementGuid>4e508131-5e0f-4c8d-a6f8-24a14fb6e6bb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
