<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Tambah Saldo_qty</name>
   <tag></tag>
   <elementGuidId>22b121fa-c722-4d21-97a4-24c51a0642c5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#qty</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='qty']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f25eb6f6-47ed-4e68-b6ae-02861037434f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>tel</value>
      <webElementGuid>5d543705-efda-4305-8ce3-db1c5283d494</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>mask</name>
      <type>Main</type>
      <value>separator.0</value>
      <webElementGuid>fe1da363-3179-48f6-a174-db4389871681</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>thousandseparator</name>
      <type>Main</type>
      <value>.</value>
      <webElementGuid>9aba339e-54d2-4454-9d15-a39f5ca8ceae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ng-untouched ng-dirty ng-valid</value>
      <webElementGuid>91b3cf97-ca29-4398-8760-340480fa6a49</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>qty</value>
      <webElementGuid>c8caae76-54cc-4de5-9e1d-f3689e28b77e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>e1f37a37-a983-459a-9b82-01d4912a81df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;qty&quot;)</value>
      <webElementGuid>688a8629-3edc-4046-b58f-dffd06b7180f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='qty']</value>
      <webElementGuid>6e29f7b5-2036-42fc-a057-070b4568b1b0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='xForm']/div/div[4]/app-currency/fieldset/input</value>
      <webElementGuid>6935f136-a72c-4806-9010-6e2abce13065</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//fieldset/input</value>
      <webElementGuid>384ef29f-2dfe-4e8b-8da0-593ff1bfc8d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'tel' and @id = 'qty' and @placeholder = '0']</value>
      <webElementGuid>4110fe07-e935-4de6-ab50-65cb2591edb2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
