<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Nomor Tagihan_refNo</name>
   <tag></tag>
   <elementGuidId>ff6319f4-4e7a-4f5c-a1a0-ac7ca77fab50</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#refNo</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='refNo']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ae019a2c-abbd-4783-b9be-b4dbb2637326</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>77385fc6-d383-466a-b66f-9f44f92b634c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ng-untouched ng-pristine ng-invalid</value>
      <webElementGuid>06019685-0c5c-424c-8a45-a8b4f21a0793</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>refNo</value>
      <webElementGuid>938a9190-1e26-4e45-a51a-3779560cc9d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Tulis nomor tagihan</value>
      <webElementGuid>09b1f12b-21f0-4b66-b310-a53134c36b32</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>100</value>
      <webElementGuid>68aee60b-8d7e-4644-9ae6-5889e7caeba0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;refNo&quot;)</value>
      <webElementGuid>8384c1e9-75c1-4cef-aa8f-9d3aba0d468e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='refNo']</value>
      <webElementGuid>382f38e5-e331-4b39-928d-af1d7ea0db9c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='xForm']/div/div[5]/app-text/fieldset/div/input</value>
      <webElementGuid>e6ae1176-811b-4fb8-be7d-918c569332a2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//fieldset/div/input</value>
      <webElementGuid>3758df8c-169c-49a5-b5b9-1ca1d3c156e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'refNo' and @placeholder = 'Tulis nomor tagihan']</value>
      <webElementGuid>50592bf4-ce73-45ed-a94f-90ac23a8d992</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
