<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Verifikasi Dukcapil Tanpa Biometrik_D_8fb83e</name>
   <tag></tag>
   <elementGuidId>a18f5eb8-eb0d-4cf4-a4f1-c6f3a88afd05</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='DUKCAPIL_NOBIO@DJP']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ee734322-2b23-4cdd-aac1-7e4f36646abf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>dadd8c53-6514-4863-b74f-510414e41dce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-check-input ng-star-inserted</value>
      <webElementGuid>2428a8d2-b2d8-46e9-a657-6303259364d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>DUKCAPIL_NOBIO@DJP</value>
      <webElementGuid>5c822f13-cfb7-468d-9b4a-ae751cf7f86e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;DUKCAPIL_NOBIO@DJP&quot;)</value>
      <webElementGuid>bf3f24af-18f7-43c1-a431-fdd826f5bc36</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='DUKCAPIL_NOBIO@DJP']</value>
      <webElementGuid>ad22eb33-2662-43b7-aa7c-16d4c3940968</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[114]/input</value>
      <webElementGuid>c5672281-5cec-4e89-b1fd-3a6c07999082</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @id = 'DUKCAPIL_NOBIO@DJP']</value>
      <webElementGuid>5075f380-bb54-44ff-b3b7-beb7c812937f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
