<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Pilih Tenant_ng-arrow-wrapper</name>
   <tag></tag>
   <elementGuidId>90ea1764-2ef5-4312-a8e1-565bb0237079</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.ng-arrow-wrapper</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//ng-select[@id='tenantCode']/div/span[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>f67f1d19-96a3-4af1-83c7-c78d5aac7091</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-arrow-wrapper</value>
      <webElementGuid>8f50b966-4810-435b-a549-8db60c4355f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;xForm&quot;)/div[@class=&quot;row&quot;]/div[@class=&quot;col-12&quot;]/app-select[1]/div[@class=&quot;form-group ng-untouched ng-pristine ng-invalid ng-star-inserted&quot;]/ng-select[@id=&quot;tenantCode&quot;]/div[@class=&quot;ng-select-container ng-has-value&quot;]/span[@class=&quot;ng-arrow-wrapper&quot;]</value>
      <webElementGuid>5697ae8b-0c36-46ab-a473-f5f1560480f0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ng-select[@id='tenantCode']/div/span[2]</value>
      <webElementGuid>f6f7ea0e-11ff-4639-a779-c8bfd2979a07</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pilih Tenant'])[1]/following::span[3]</value>
      <webElementGuid>29f775aa-3f09-47a2-8b7d-7e589c242365</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pilih tenant'])[1]/following::span[5]</value>
      <webElementGuid>22da7004-daec-4ebd-8062-88a1c772d1b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pilih Tenant'])[2]/preceding::span[2]</value>
      <webElementGuid>6fb6eb0c-8965-4613-8c07-69d3ff1dedeb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SMS Finance'])[1]/preceding::span[3]</value>
      <webElementGuid>02dfd7dc-fa1e-4e01-8d70-5b1720ef64e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[2]</value>
      <webElementGuid>ab53f543-720d-449a-a11e-497f2867b3d1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
