<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>framelogin</name>
   <tag></tag>
   <elementGuidId>a59f7d24-0e35-423e-951b-f90e03e8f6e6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.col-12 > div.row</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>/html/body/app-root/app-full-layout/div/div[2]/div/div[2]/app-edit-my-profile/div[2]/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>b01b6e81-6487-4acf-ba12-7cdcde1b45eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>row</value>
      <webElementGuid>46b0d60f-e110-4c0d-b2c5-0e527b90d605</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Email *Nama Perusahaan *Industri WebsiteJabatan KerjaNama Depan *Nama Belakang *Jenis Kelamin Pria WanitaNomor HPKode NegaraKembaliSimpan</value>
      <webElementGuid>cd3759ce-bba4-4593-9e6c-056263f04a6e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;vertical-layout menu-hide navbar-static  pace-done&quot;]/app-root[1]/app-full-layout[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;wrapper&quot;]/div[@class=&quot;main-panel&quot;]/div[@class=&quot;main-content&quot;]/div[@class=&quot;content-wrapper&quot;]/app-edit-my-profile[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;container-fluid&quot;]/div[@class=&quot;row bg-white rounded&quot;]/div[@class=&quot;col-12&quot;]/div[@class=&quot;row&quot;]</value>
      <webElementGuid>8996a6ec-be08-4edb-a56e-e1cf66fc6918</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Edit Profil'])[1]/following::div[4]</value>
      <webElementGuid>7a97c882-373d-4320-94fb-763f70a540af</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Saldo'])[1]/following::div[15]</value>
      <webElementGuid>f8fa1382-4057-4adb-b422-06a840c08f0b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div</value>
      <webElementGuid>57622e3c-7194-44ed-a3dc-37f8a96ca25c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Email *Nama Perusahaan *Industri WebsiteJabatan KerjaNama Depan *Nama Belakang *Jenis Kelamin Pria WanitaNomor HPKode NegaraKembaliSimpan' or . = 'Email *Nama Perusahaan *Industri WebsiteJabatan KerjaNama Depan *Nama Belakang *Jenis Kelamin Pria WanitaNomor HPKode NegaraKembaliSimpan')]</value>
      <webElementGuid>2ae5e579-6d05-43e3-a9a8-aa7f5651a71a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
