<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__NPWP</name>
   <tag></tag>
   <elementGuidId>75b50caf-e119-4faf-a2f1-9ebf22394b4a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;tenantNpwp&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;tenantNpwp&quot;]</value>
      <webElementGuid>92451175-d9bd-4ec9-b65f-7c327287eb58</webElementGuid>
   </webElementProperties>
</WebElementEntity>
