<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>radio_Perusahaan</name>
   <tag></tag>
   <elementGuidId>e8ad56c2-3ffa-4015-97ea-cdaa2bb73c4c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@type = 'radio' and @value = 'Company']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/app-root/app-full-layout/div/div[2]/div/div[2]/app-edit-my-profile/div[2]/div/div/div/div[2]/form/div[7]/div[1]/label/input</value>
      <webElementGuid>6713253c-376b-4a11-9997-54aecd9f8138</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>5bce1f72-88f0-4940-9844-10c56cf571c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Company</value>
      <webElementGuid>55e11bcd-8e0a-4f82-b597-f1980be280d4</webElementGuid>
   </webElementProperties>
</WebElementEntity>
