<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_Buat Akun_a-2trq71fdezk3</name>
   <tag></tag>
   <elementGuidId>d4e18173-879c-4e04-b349-4c1725e5944d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@name='a-2trq71fdezk3']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>iframe[name=&quot;a-2trq71fdezk3&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>c169f921-b802-413f-8abc-90340dc6f052</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>reCAPTCHA</value>
      <webElementGuid>fd688cfb-cafb-41d2-8e3f-125b71fe2729</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://www.google.com/recaptcha/api2/anchor?ar=1&amp;k=6LcDnrckAAAAAOvOHY_-Rd-L-T6KyqwMtloQn_61&amp;co=aHR0cDovL2dka3dlYnN2cjo0MTAw&amp;hl=id&amp;type=image&amp;v=MuIyr8Ej74CrXhJDQy37RPBe&amp;theme=light&amp;size=normal&amp;cb=jwcjupazijm0</value>
      <webElementGuid>456df6e6-5546-4463-a700-d5024440c5aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>304</value>
      <webElementGuid>1393c116-0e91-4247-ad0e-88bbac4a4b0c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>78</value>
      <webElementGuid>5eb7f689-e682-4cca-8b65-11e1ccfceac2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>presentation</value>
      <webElementGuid>0b032067-41bc-4333-8e48-e7037ec25fbf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>a-2trq71fdezk3</value>
      <webElementGuid>33a987fa-aa52-48b4-818a-8003cea4422f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>9ee6d34a-a18d-4781-9998-384a0f71146d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scrolling</name>
      <type>Main</type>
      <value>no</value>
      <webElementGuid>5dc0296a-5b38-4fb8-9794-370d14949180</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>sandbox</name>
      <type>Main</type>
      <value>allow-forms allow-popups allow-same-origin allow-scripts allow-top-navigation allow-modals allow-popups-to-escape-sandbox</value>
      <webElementGuid>8f5fca6f-d423-4b6f-ba7d-219db4065c06</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ngx_captcha_id_9374&quot;)/div[1]/div[1]/iframe[1]</value>
      <webElementGuid>aed6d31d-73f9-4f14-a955-f68fe97e40cd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@name='a-2trq71fdezk3']</value>
      <webElementGuid>70d16fce-7db1-4ee4-8cba-a79b16496655</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ngx_captcha_id_9374']/div/div/iframe</value>
      <webElementGuid>31eecce6-10c3-4027-959e-ef061fefd286</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>f66a82d7-1773-4a2a-bb30-e1e1907df5a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@title = 'reCAPTCHA' and @src = 'https://www.google.com/recaptcha/api2/anchor?ar=1&amp;k=6LcDnrckAAAAAOvOHY_-Rd-L-T6KyqwMtloQn_61&amp;co=aHR0cDovL2dka3dlYnN2cjo0MTAw&amp;hl=id&amp;type=image&amp;v=MuIyr8Ej74CrXhJDQy37RPBe&amp;theme=light&amp;size=normal&amp;cb=jwcjupazijm0' and @name = 'a-2trq71fdezk3']</value>
      <webElementGuid>fa4a5bd2-69ce-46cb-9a95-84fed5114039</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
