<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_Buat Akun Anda Sekarang_c-2trq71fdezk3</name>
   <tag></tag>
   <elementGuidId>4fc54852-4dff-4186-b64b-89e32d4ac75b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@name='c-2trq71fdezk3']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>iframe[name=&quot;c-2trq71fdezk3&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>770aaa20-4399-46cb-833e-179d2bb601ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>masa berlaku tantangan recaptcha akan berakhir dalam dua menit</value>
      <webElementGuid>2c55fe3b-442e-4162-8c5a-f458ff68da10</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://www.google.com/recaptcha/api2/bframe?hl=id&amp;v=MuIyr8Ej74CrXhJDQy37RPBe&amp;k=6LcDnrckAAAAAOvOHY_-Rd-L-T6KyqwMtloQn_61</value>
      <webElementGuid>7fc644a2-5b3b-4701-9b70-a3aca19396ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>c-2trq71fdezk3</value>
      <webElementGuid>9d19eb8e-6248-463f-8e70-93f82733cabf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>fa17731f-04ab-48ef-abe1-964a5452c775</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scrolling</name>
      <type>Main</type>
      <value>no</value>
      <webElementGuid>359b85b1-fc16-491d-ac70-7f3713d7cb44</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>sandbox</name>
      <type>Main</type>
      <value>allow-forms allow-popups allow-same-origin allow-scripts allow-top-navigation allow-modals allow-popups-to-escape-sandbox</value>
      <webElementGuid>17b1d787-5b56-4a5c-96f8-b95c396d1bda</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;auth-page blank-page pace-done pace-done&quot;]/div[5]/div[4]/iframe[1]</value>
      <webElementGuid>09903c78-26e8-49b9-bf62-d645558bd167</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@name='c-2trq71fdezk3']</value>
      <webElementGuid>f386888e-d0c3-40a6-b063-e253338d607e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div[4]/iframe</value>
      <webElementGuid>72c5792b-39ae-4e7f-a4a6-20849202c135</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@title = 'masa berlaku tantangan recaptcha akan berakhir dalam dua menit' and @src = 'https://www.google.com/recaptcha/api2/bframe?hl=id&amp;v=MuIyr8Ej74CrXhJDQy37RPBe&amp;k=6LcDnrckAAAAAOvOHY_-Rd-L-T6KyqwMtloQn_61' and @name = 'c-2trq71fdezk3']</value>
      <webElementGuid>386ecfdb-5391-4d6a-8a59-474f3f0156b1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
