<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Buat Akun_form-control is-invalid ng-_7788b4_1_2</name>
   <tag></tag>
   <elementGuidId>18a19ec6-7ff3-4951-9eb1-da60cbe7f745</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//input[@type='password'])[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input.form-control.is-invalid.ng-untouched.ng-pristine.ng-invalid</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>5fc17c74-e651-45bc-9e5f-469472a97d3a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>confirmPassword</value>
      <webElementGuid>e24b5d8e-957b-418e-832a-e63907616104</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>36</value>
      <webElementGuid>0538c2d9-7aa0-4e89-838d-9f9464123b6b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control is-invalid ng-untouched ng-pristine ng-invalid</value>
      <webElementGuid>6b9dbcf5-9302-4d0a-8ae3-0bfa2c65d07d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-name</name>
      <type>Main</type>
      <value>confirmPassword</value>
      <webElementGuid>39427d54-8cf9-4d41-92dc-606c4efaee45</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>504e1c55-e84d-4121-9c83-4f04dfb5a5b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Ketik Ulang Kata Sandi</value>
      <webElementGuid>87ce64b1-840c-4e5b-89c7-af787b71955d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-is-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>d1a5cd47-5b81-4cda-aaca-5addfca4b3a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-ng-class</name>
      <type>Main</type>
      <value>[object Object]</value>
      <webElementGuid>af6acedc-8e54-45b8-8a82-64f59c4868d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mat-tab-content-0-1&quot;)/div[@class=&quot;mat-tab-body-content ng-tns-c240-2 ng-trigger ng-trigger-translateTab&quot;]/form[@class=&quot;ng-star-inserted ng-touched ng-dirty ng-invalid&quot;]/div[@class=&quot;form-group&quot;]/div[@class=&quot;input&quot;]/input[@class=&quot;form-control is-invalid ng-untouched ng-pristine ng-invalid&quot;]</value>
      <webElementGuid>71fdd26a-325c-4869-bf3d-1e656bccf9b3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@type='password'])[2]</value>
      <webElementGuid>76364f2a-6f3e-4857-ac4e-b7a2de541fd0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//mat-tab-body[@id='mat-tab-content-0-1']/div/form/div[4]/div/input</value>
      <webElementGuid>0b52b714-0d2c-4abd-bd0a-269abe68a0be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/input</value>
      <webElementGuid>9a0745e0-8c74-4a48-b487-34dada55b993</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'password' and @placeholder = 'Ketik Ulang Kata Sandi']</value>
      <webElementGuid>f1fceb8b-c529-427a-86b9-b25cf6a48493</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
