<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>EmailPrefill</name>
   <tag></tag>
   <elementGuidId>25c31682-c87b-4c1e-9bc3-94bc3e250c5e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;email&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;email&quot;]</value>
      <webElementGuid>e69834a6-9611-4327-bb55-c8437bbc1825</webElementGuid>
   </webElementProperties>
</WebElementEntity>
