<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Statusactive</name>
   <tag></tag>
   <elementGuidId>9dc4d07f-c78e-4271-94b7-e00ef856b0d8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@ng-reflect-ng-item-label = 'Aktif' and @class = 'ng-option-label ng-star-inserted']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;a4b847a7457b-0&quot;]/span</value>
      <webElementGuid>b5aaf273-3f40-4383-87b7-1b20d4e5c18e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-ng-item-label</name>
      <type>Main</type>
      <value>Aktif</value>
      <webElementGuid>35eeb921-ebe2-4644-a05e-d8d8d36fcee2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-option-label ng-star-inserted</value>
      <webElementGuid>91134daf-63ce-4b77-840d-a09885c923f4</webElementGuid>
   </webElementProperties>
</WebElementEntity>
