<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Active</name>
   <tag></tag>
   <elementGuidId>488a6886-7ae7-4be3-9040-38f776406bae</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#afadc98575a0-0</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='afadc98575a0-0']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>5b14ff76-968c-4ac7-94b2-444da38a9a56</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-option ng-option-selected ng-star-inserted ng-option-marked</value>
      <webElementGuid>51db0519-2575-4840-8744-0e37e8eab147</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>72e658c9-74a0-4626-bad9-9342c79ba658</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>4b646325-73c4-48a4-85ff-ad509160e785</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>afadc98575a0-0</value>
      <webElementGuid>59719cac-3930-4938-8424-e2ff260d748d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Active</value>
      <webElementGuid>a6468565-b399-488e-a4c3-c482d12d0aaf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;afadc98575a0-0&quot;)</value>
      <webElementGuid>067d591e-4618-4516-a3b9-f7c491bf5908</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='afadc98575a0-0']</value>
      <webElementGuid>3b380095-43da-4cc8-98b6-5e3f29b1d618</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ng-dropdown-panel[@id='afadc98575a0']/div/div[2]/div</value>
      <webElementGuid>08a287f6-afe7-4a7b-8cd6-0b36645b968d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Active'])[1]/following::div[5]</value>
      <webElementGuid>236e6f2b-4dbc-46e0-9629-7000147a9f0e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Enter activation status'])[1]/following::div[6]</value>
      <webElementGuid>d4560bb6-a527-4d41-beab-3cd149597fcb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Inactive'])[1]/preceding::div[1]</value>
      <webElementGuid>16ba63a5-6fe6-42ff-96c3-ef39ff26f18d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//ng-dropdown-panel/div/div[2]/div</value>
      <webElementGuid>3dc99a3b-c9bf-4aac-b196-552686bffb3d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'afadc98575a0-0' and (text() = 'Active' or . = 'Active')]</value>
      <webElementGuid>b1e7bb5f-46d8-4e20-8cea-8c90acbc9569</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
