<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_confirmNewPassword</name>
   <tag></tag>
   <elementGuidId>e615303a-2c0d-4ac0-a800-b5ba87c266e7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='confirmNewPassword']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#confirmNewPassword</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>df16bc40-dc15-476c-b1a1-7e4b87a37498</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ng-untouched ng-pristine ng-invalid</value>
      <webElementGuid>b7f7d42c-95ce-4abf-93ca-29eb8d91155d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-name</name>
      <type>Main</type>
      <value>confirmNewPassword</value>
      <webElementGuid>b5df9757-a799-4d4a-b9b5-d22e8319e4d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>confirmNewPassword</value>
      <webElementGuid>81ee4e33-7ea1-420d-afe4-6937e737230a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>fdfe1fa4-4804-450e-b3c6-608f21496678</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Konfirmasi Kata Sandi Baru</value>
      <webElementGuid>d4a3537f-a319-4496-8be8-600ce6e33ffa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>076dc2cc-e902-492d-a959-e7a18b89ae5d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;confirmNewPassword&quot;)</value>
      <webElementGuid>2760be84-005e-4fce-8f34-f4f7dd3317f5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='confirmNewPassword']</value>
      <webElementGuid>a45ed6c4-d71b-4fd9-b5db-6f7b59ba5e75</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='msxForm']/div/div[2]/app-question/app-password/fieldset/div/input</value>
      <webElementGuid>f1c5aa51-c14e-489e-9113-2c1591144ca9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/app-question/app-password/fieldset/div/input</value>
      <webElementGuid>9cdc6421-7c65-4c8b-a14a-3cf287687e58</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'confirmNewPassword' and @type = 'password' and @placeholder = 'Konfirmasi Kata Sandi Baru']</value>
      <webElementGuid>d04dcc4a-094a-402f-9963-b97dd0f19c58</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
