<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>skiptoLast_page</name>
   <tag></tag>
   <elementGuidId>5cabfc2a-4734-42fe-afa5-531159619d95</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>i.datatable-icon-skip</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@class = 'datatable-icon-skip']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@class = 'datatable-icon-skip']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>9ad2746a-85ba-4333-8565-20858eaa87fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>datatable-icon-skip</value>
      <webElementGuid>3ffa4c5c-d6dc-4b5c-98dd-fe3d78037bcc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value></value>
      <webElementGuid>ccda3356-5646-47b4-b352-d7b6f1672d1f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[7]/a/i</value>
      <webElementGuid>f5d8ee86-ec9d-43a4-8d38-50d80a19cad5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
